### ISSUE TITLE
Support for summary data

### ISSUE THREAD

**Issue by gaow** [vatlab/VariantTools#1]
I'd like to start some brainstorming here for the next stage of the project. The first thing popping to my mind is the support for summary data. Numerous methods these days are developed based-off summary statistics. Data integration of such kind will continue to be popular. Currently only `vtools_report meta_analysis` uses summary statistics data. The behavior is more like a standalone meta analysis program branded with VAT. We need more work on the design and implementation to support summary data.

**Comment by BoPeng** [comment]
Moved to VariantAssociationTools/VAT
