### ISSUE TITLE
How to show samples with heterogyzous genotype?

### ISSUE THREAD

**Issue by mullinyu** [vatlab/VariantTools#102]
I can do the following to list the samples having that allele. But, how can I if I would like to list those samples with heterogyzous genotype (wildtype and alternate)?

vtools select variant 'chr="3" AND pos=14187449 AND ref="G" AND alt="T"'-o chr pos ref alt dbSNP.name "samples()"

Thanks!

**Comment by BoPeng** [comment]
DId you try

```
samples('geno_filter=GT=1')
```
as described [here](https://vatlab.github.io/vat-docs/documentation/functions/samples/)?

**Comment by mullinyu** [comment]
Thanks! It works perfectly!!! Sorry I didn't read that page.
