### ISSUE TITLE
--from_stat vtools 3.0.2 for Python 3.7.3

### ISSUE THREAD

**Issue by freedomq8** [vatlab/VariantTools#106]
Hello,

I am facing an issue "" when I used command
`vtools update variant --from_stat 'total=#(GT)' 'num=#(alt)' 'het=#(het)' 'hom=#(hom)' 'other=#(other)' 'minDP=min(DP_geno)' 'maxDP=max(DP_geno)' 'meanDP=avg(DP_geno)' 'maf=maf()' 'missing=#(missing)' `

when I use the above command its either freeze/stuck 
`Counting variants:   0.0% [>                                      ]  in 00:00:00`
or 
`ERROR ambiguous column name chr`

that I didn't face using vtools 2.7.0 for Python 2.7.12

any suggestions?

**Comment by BoPeng** [comment]
@jma7 Could you try to reproduce this?

**Comment by jma7** [comment]
@freedomq8 Would you please try to create another project, import your data again and try the update command?

**Comment by BoPeng** [comment]
We suspect that you are running vtools 3 on a vtools 2 project.

**Comment by freedomq8** [comment]
hi again, 
its not vtools3 on vtools2 project as i made a new folder for that but will keep this in mind for the future. As i needed the results quickly i had to move to vtool2 and ran the same scripts in a new folder and didn't get any of the above mentioned error. 
so i am sure its python3 and vtool3 issue.

**Comment by BoPeng** [comment]
@freedomq8 It would be good if you could upload (or send me private email) some sample data (e.g. first 1000 lines of your vcf file) and commands to reproduce the problem.

**Comment by freedomq8** [comment]
I sent the files but I think it was bounced back due to GitHub limits 4mb per file. I can send it to via email


________________________________

**Comment by BoPeng** [comment]
You can email to bpeng@mdanderson.org

**Comment by jma7** [comment]
@freedomq8 Hi, we recently made a new release [v3.0.3](https://github.com/vatlab/VariantTools/releases/tag/v3.0.3) to address the issues when importing several VCF files with different samples. I tried your commands which works fine with the new release. However I notice that you have some variants on ChrM which are not supported in current version. I will fix this issue in the next release. Meanwhile, you don't have to shift to Python2.7 version. When you initiate new project, you could do
``` vtools init -f test --store sqlite``` to use python 3 and Sqlite for storage.

**Comment by freedomq8** [comment]
Hi
i got this error when when i try to install it
`Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    from setuptools import find_packages, setup, Extension
ModuleNotFoundError: No module named 'setuptools'
`

i dont get the same error when i try the conda method ?

**Comment by freedomq8** [comment]
HI again, 

I manage to install v3.0.3 after installing its decencies scipy Cython numpy setuptools. I tried to the following commands with one vcf file to see if its works;
vtools init  test
vtools import diabetes.for.association.vcf --var_info DP filter --geno_info DP_geno --build hg19 -j21
vtools phenotype --from_file phenotypes.csv --delimiter ","
vtools execute ANNOVAR geneanno --annovar_path /home/daruma/soft/annovar/
vtools use refGene
vtools update variant --from_stat 'total=#(GT)' 'num=#(alt)' 'het=#(het)' 'hom=#(hom)' 'other=#(other)' 'maf=maf()' 'fq=maf()' 'missing=#(missing)' 
vtools select variant "filter='PASS'" --t variantsP 'Passsed variants'
echo -e "\e[1m\e[46mVtools passed variant state update for phenotype 1 \e[0m"
vtools update variantsP --from_stat 'num_gt_case=#(GT)' 'num_var_alleles_case=#(alt)' --samples phenotype=1
`
after the last command i got this message and nothing happens for an hour but the cpu cores are at 100%
`#INFO: Reading genotype info for processing....`

so i tried the commands you recommend
after i deleted all the files previously generated as well as the hidden files
`vtools init diabetes -f test --store sqlite`
`vtools init -f test --store sqlite`
but i got this message
`vtools: error: unrecognized arguments: test`

any suggestions to what i am doing wrong ?

**Comment by BoPeng** [comment]
Many thanks for the bug report, we will have a look as soon as we can.

**Comment by freedomq8** [comment]
Thanks, using --store sqlite by its own solved the issue.
