### ISSUE TITLE
KING ERROR: Segmentation fault (core dumped)  (return code 139).

### ISSUE THREAD

**Issue by freedomq8** [vatlab/VariantTools#107]
Hello, 

I am getting this error when trying to execute KING command on vtools 2.7.0 for Python 2.7.12 on mac laptop. I thought I came across this problem before but not sure how did I solve it but I am sure its either using different machine or different versions of KING and/or plink.
```
INFO: Executing KING.king_0: Load specified snapshot if a snapshot is specified. Otherwise use the existing project.
INFO: Executing KING.king_10: Check the existence of KING and PLINK command.
INFO: Command /home/tutankhmun/soft/king is located.
INFO: Command /home/tutankhmun/soft/plink is located.
INFO: Executing KING.king_20: Write selected variant and samples in tped format
INFO: Reuse existing /mnt/c/diabetes/.vtools_cache/KING.tped
INFO: Executing KING.king_21: Rename tfam file to match tped file
INFO: Reuse existing /mnt/c/diabetes/.vtools_cache/KING.tfam
INFO: Executing KING.king_30: Calculate LD pruning candidate list with a cutoff of R^2=0.5
INFO: Running /home/tutankhmun/soft/plink --noweb --tped KING.tped --tfam KING.tfam --indep-pairwise 50 5 0.5 --allow-no-sex --out KING.LD.50 under /mnt/c/diabetes/.vtools_cache
ERROR: Segmentation fault (core dumped)
ERROR:
ERROR: Failed to execute step king_30: Execution of command '/home/tutankhmun/soft/plink --noweb --tped KING.tped --tfam KING.tfam --indep-pairwise 50 5 0.5 --allow-no-sex --out KING.LD.50' failed after 00:00:00 (return code 139).
```
any suggestions?
thanks

**Comment by freedomq8** [comment]
Hello again, i ran KING on vtools.2.70 for Python 2.7.12 on PC and got another error. is this king specific issue or vtools ?

`INFO: Executing KING.king_0: Load specified snapshot if a snapshot is specified. Otherwise use the existing project.
INFO: Executing KING.king_10: Check the existence of KING and PLINK command.
INFO: Command /home/daruma/soft/king is located.
INFO: Command /home/daruma/soft/plink is located.
INFO: Executing KING.king_20: Write selected variant and samples in tped format
WARNING: Size of existing file differ from recorded file: diabetes.proj
INFO: Running vtools export rare_nonsyn_vars --format tped --samples "1" | awk '{$2=$1"_"$4;$3=0;print $0}' > cache/KING.tped
INFO: Executing KING.king_21: Rename tfam file to match tped file
INFO: Running mv rare_nonsyn_vars.tfam cache/KING.tfam
ERROR: mv: symbol lookup error: mv: undefined symbol: mode_to_security_class
ERROR: 
ERROR: Failed to execute step king_21: Execution of command 'mv rare_nonsyn_vars.tfam cache/KING.tfam' failed after 00:00:00 (return code 127).`

any suggestion ?

thanks

**Comment by BoPeng** [comment]
Can you try to run the command manually

```
/home/tutankhmun/soft/plink --noweb --tped KING.tped --tfam KING.tfam --indep-pairwise 50 5 0.5 --allow-no-sex --out KING.LD.50
```
and see if all input files are there and what error messages it gives?

**Comment by freedomq8** [comment]
/home/tutankhmun/soft/plink --noweb --tped KING.tped --tfam KING.tfam --indep-pairwise 50 5 0.5 --allow-no-sex --out KING.LD.50
​
@----------------------------------------------------------@​
|        PLINK!       |     v1.07      |   10/Aug/2009     |​
|----------------------------------------------------------|​
|  (C) 2009 Shaun Purcell, GNU General Public License, v2  |​
|----------------------------------------------------------|​
|  For documentation, citation & bug-report instructions:  |​
|        http://pngu.mgh.harvard.edu/purcell/plink/        |​
@----------------------------------------------------------@​
​
Segmentation fault (core dumped)

this is the error I got

________________________________

**Comment by BoPeng** [comment]
Then perhaps you can install a different version of plink and/or run plink on other files to check it is properly installed? seqfault could be installation problem, or because invalid input file, in which case you should manually check the input files.

**Comment by freedomq8** [comment]
I tried different versions of plink but still the same error. it could be OS issue as for this machine I am using ubuntu on windows. someone mentioned having the same issue on ubuntu on windows with plink

https://groups.google.com/forum/#!topic/plink2-users/m051Ez2MJdM
[http://www.google.com/images/icons/product/groups-128.png]<https://groups.google.com/forum/#!topic/plink2-users/m051Ez2MJdM>
Segmentation fault (core dumped),<https://groups.google.com/forum/#!topic/plink2-users/m051Ez2MJdM>
Posted 3/8/18 9:49 PM, 6 messages
groups.google.com

however I am having another error with KING on ubuntu by its own with error code 127

(base) daruma@daruma:/media/daruma/sea8/diabetic$ vtools execute KING  --var_table rare_nonsyn_vars --king_path=/home/daruma/soft --plink_path=/home/daruma/soft
INFO: Executing KING.king_0: Load specified snapshot if a snapshot is specified. Otherwise use the existing project.​
INFO: Executing KING.king_10: Check the existence of KING and PLINK command.​
INFO: Command /home/daruma/soft/king is located.​
INFO: Command /home/daruma/soft/plink is located.​
INFO: Executing KING.king_20: Write selected variant and samples in tped format​
INFO: Reuse existing cache/KING.tped​
INFO: Executing KING.king_21: Rename tfam file to match tped file​
INFO: Running mv rare_nonsyn_vars.tfam cache/KING.tfam​
ERROR: mv: symbol lookup error: mv: undefined symbol: mode_to_security_class​
ERROR: ​
ERROR: Failed to execute step king_21: Execution of command 'mv rare_nonsyn_vars.tfam cache/KING.tfam' failed after 00:00:00 (return code 127).​
​
​


________________________________

**Comment by freedomq8** [comment]
hello, 

I manage to solve code 139 by using another plink version from this source http://s3.amazonaws.com/plink1-assets/dev/plink_linux_x86_64.zip

then I got another 127 that I manage to manually move/rename the file to cache directory and delete king21 step from KING.pipeline

but now I am getting code 1 error

` vtools execute KING  --var_table rare_nonsyn_vars --king_path=/home/tutankhmun/soft --plink_path=/home/tutankhmun/soft
INFO: Executing KING.king_0: Load specified snapshot if a snapshot is specified. Otherwise use the existing project.
INFO: Executing KING.king_10: Check the existence of KING and PLINK command.
INFO: Command /home/tutankhmun/soft/king is located.
INFO: Command /home/tutankhmun/soft/plink is located.
INFO: Executing KING.king_20: Write selected variant and samples in tped format
INFO: Reuse existing /mnt/c/diabetes/.vtools_cache/KING.tped
INFO: Executing KING.king_21: Rename tfam file to match tped file
INFO: Reuse existing /mnt/c/diabetes/.vtools_cache/KING.tfam
INFO: Executing KING.king_30: Calculate LD pruning candidate list with a cutoff of R^2=0.5
INFO: Reuse existing /mnt/c/diabetes/.vtools_cache/KING.LD.50.prune.in
INFO: Executing KING.king_31: LD pruning from pre-calculated list
INFO: Reuse existing /mnt/c/diabetes/.vtools_cache/KING.bed
INFO: Executing KING.king_41: Global ancestry inference
INFO: Running /home/tutankhmun/soft/king -b KING.bed --mds --ibs --prefix KING- under /mnt/c/diabetes/.vtools_cache
ERROR:
ERROR: Failed to execute step king_41: Execution of command '/home/tutankhmun/soft/king -b KING.bed --mds --ibs --prefix KING-' failed after 00:00:00 (return code 1).
tutankhmun@daruma:/mnt/c/diabetes$ sudo vtools execute KING  --var_table rare_nonsyn_vars --king_path=/home/tutankhmun/soft --plink_path=/home/tutankhmun/soft
INFO: Executing KING.king_0: Load specified snapshot if a snapshot is specified. Otherwise use the existing project.
INFO: Executing KING.king_10: Check the existence of KING and PLINK command.
INFO: Command /home/tutankhmun/soft/king is located.
INFO: Command /home/tutankhmun/soft/plink is located.
INFO: Executing KING.king_20: Write selected variant and samples in tped format
INFO: Reuse existing /mnt/c/diabetes/.vtools_cache/KING.tped
INFO: Executing KING.king_21: Rename tfam file to match tped file
INFO: Reuse existing /mnt/c/diabetes/.vtools_cache/KING.tfam
INFO: Executing KING.king_30: Calculate LD pruning candidate list with a cutoff of R^2=0.5
INFO: Reuse existing /mnt/c/diabetes/.vtools_cache/KING.LD.50.prune.in
INFO: Executing KING.king_31: LD pruning from pre-calculated list
INFO: Reuse existing /mnt/c/diabetes/.vtools_cache/KING.bed
INFO: Executing KING.king_41: Global ancestry inference
INFO: Running /home/tutankhmun/soft/king -b KING.bed --mds --ibs --prefix KING- under /mnt/c/diabetes/.vtools_cache
ERROR:
ERROR: Failed to execute step king_41: Execution of command '/home/tutankhmun/soft/king -b KING.bed --mds --ibs --prefix KING-' failed after 00:00:00 (return code 1).`


i am not sure if its OS error or installing issue. is there a VM with vtools installed or docker of vtools ?
