### ISSUE TITLE
KING ERROR: Failed to execute step king_41: /KING-pc.ped does not exist

### ISSUE THREAD

**Issue by freedomq8** [vatlab/VariantTools#109]
Hi,

On both vtools.7 and 3.0.3 I am getting the same error when execute KING
`vtools execute KING  --var_table rare_nonsyn_vars --king_path=/home/tutankhmun/soft --plink_path=/home/tutankhmun/soft -j7`

error
`INFO: Executing KING.king_0: Load specified snapshot if a snapshot is specified. Otherwise use the existing project.
INFO: Executing KING.king_10: Check the existence of KING and PLINK command.
INFO: Command /home/tutankhmun/soft/king is located.
INFO: Command /home/tutankhmun/soft/plink is located.
INFO: Executing KING.king_20: Write selected variant and samples in tped format
INFO: Running vtools export rare_nonsyn_vars --format tped --samples "1" | awk '{$2=$1"_"$4;$3=0;print $0}' > /mnt/c/diabetes/.vtools_cache/KING.tped
INFO: Executing KING.king_21: Rename tfam file to match tped file
INFO: Running mv rare_nonsyn_vars.tfam /mnt/c/diabetes/.vtools_cache/KING.tfam
INFO: Executing KING.king_30: Calculate LD pruning candidate list with a cutoff of R^2=0.5
INFO: Running /home/tutankhmun/soft/plink --noweb --tped KING.tped --tfam KING.tfam --indep-pairwise 50 5 0.5 --allow-no-sex --out KING.LD.50 under /mnt/c/diabetes/.vtools_cache
INFO: Executing KING.king_31: LD pruning from pre-calculated list
INFO: Running /home/tutankhmun/soft/plink --noweb --tped KING.tped --tfam KING.tfam --extract KING.LD.50.prune.in --no-parents --no-sex --no-pheno --maf 0.01 --make-bed --out KING under /mnt/c/diabetes/.vtools_cache
INFO: Executing KING.king_41: Global ancestry inference
INFO: Running /home/tutankhmun/soft/king -b KING.bed --mds --ibs --prefix KING- under /mnt/c/diabetes/.vtools_cache
ERROR: Failed to execute step king_41: Output file /mnt/c/diabetes/.vtools_cache/KING-pc.ped does not exist after completion of the job.`

 I added sudo as well to check if its rights issue but error 

`ERROR: Failed to execute step king_41: Execution of command '/home/tutankhmun/soft/king -b KING.bed --mds --ibs --prefix KING-' failed after 00:00:00 (return code 1).`

this is the files in .vtools_cache folder

`tutankhmun@daruma:/mnt/c/diabetes/.vtools_cache$ ls -lh
total 140M
-rwxrwxrwx 1 tutankhmun tutankhmun  12M May 28 13:35 annovar_input
-rwxrwxrwx 1 tutankhmun tutankhmun  36M May 28 13:37 annovar_input.exonic_variant_function
-rwxrwxrwx 1 tutankhmun tutankhmun 3.2K May 28 13:37 annovar_input.log
-rwxrwxrwx 1 tutankhmun tutankhmun  21M May 28 13:37 annovar_input.variant_function
-rwxrwxrwx 1 tutankhmun tutankhmun   53 Jun  5 14:39 annovar.path
-rwxrwxrwx 1 tutankhmun tutankhmun 4.2K Jun 16 13:54 KING.bed
-rwxrwxrwx 1 tutankhmun tutankhmun  569 Jun 16 13:54 KING.bim
-rwxrwxrwx 1 tutankhmun tutankhmun  22K Jun 16 13:54 KING.fam
-rwxrwxrwx 1 tutankhmun tutankhmun 2.5K Jun 16 13:54 KING.LD.50.log
-rwxrwxrwx 1 tutankhmun tutankhmun  14K Jun 16 13:54 KING.LD.50.nosex
-rwxrwxrwx 1 tutankhmun tutankhmun 218K Jun 16 13:54 KING.LD.50.prune.in
-rwxrwxrwx 1 tutankhmun tutankhmun  18K Jun 16 13:54 KING.LD.50.prune.out
-rwxrwxrwx 1 tutankhmun tutankhmun 1.2K Jun 16 13:54 KING.log
-rwxrwxrwx 1 tutankhmun tutankhmun  14K Jun 16 13:54 KING.nosex
-rwxrwxrwx 1 tutankhmun tutankhmun  22K Jun 16 13:52 KING.tfam
-rwxrwxrwx 1 tutankhmun tutankhmun   14 Jun 16 13:54 KING-TMP.dat
-rwxrwxrwx 1 tutankhmun tutankhmun  21K Jun 16 13:54 KING-TMP.ped
-rwxrwxrwx 1 tutankhmun tutankhmun  72M Jun 16 13:54 KING.tped
-rwxrwxrwx 1 tutankhmun tutankhmun  871 Jun  9 09:27 SKATJun09062702.R`

the king.log has the following info

`PLINK v1.90b6.9 64-bit (4 Mar 2019)
Options in effect:
  --extract KING.LD.50.prune.in
  --maf 0.01
  --make-bed
  --no-parents
  --no-pheno
  --no-sex
  --noweb
  --out KING
  --tfam KING.tfam
  --tped KING.tped

Hostname: daruma
Working directory: /mnt/c/diabetes/.vtools_cache
Start time: Sun Jun 16 13:54:50 2019

Note: --noweb has no effect since no web check is implemented yet.
Random number seed: 1560682490
16292 MB RAM detected; reserving 8146 MB for main workspace.
Processing .tped file.
KING-temporary.bed + KING-temporary.bim + KING-temporary.fam written.
20618 variants loaded from .bim file.
903 people (0 males, 0 females, 903 ambiguous) loaded from .fam.
Ambiguous sex IDs written to KING.nosex .
--extract: 19096 variants remaining.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 903 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is 0.934897.
19077 variants removed due to minor allele threshold(s)
(--maf/--max-maf/--mac/--max-mac).
19 variants and 903 people pass filters and QC.
Note: No phenotypes present.
--make-bed to KING.bed + KING.bim + KING.fam ... done.`

I have a suspicion that the file KING-pc.bed is the KING-TMP.bed (it doesn't have header, no phenotype, gender,age?)

`KING-TMP.ped
0 SRR2098178 0 0 0 0
1 SRR2098179 0 0 0 0
2 SRR2098180 0 0 0 0
3 SRR2098181 0 0 0 0
4 SRR2098182 0 0 0 0
5 SRR2098183 0 0 0 0
6 SRR2098184 0 0 0 0`
versions KING 2.2.1 and PLINK v1.90b6.9 64-bit

any idea how to solve this?

Thanks for your help

**Comment by jma7** [comment]
@BoPeng @freedomq8  I have encountered the same problem on Mac. The output of KING has changed in the newer version, but the KING pipeline in variantTools hasn't been updated yet. The solution is to modify the ```~/.variant_tools/pipeline/KING.pipeline```  file, try searching for ```TMP``` and change to ```pc```.

**Comment by freedomq8** [comment]
Thanks jma7 for the fast reply, 

I encountered this error on both windows/bash addon and Ubuntu on both vtools 2.7.0 and v3.0.3. i tried a different version of KING and PLINK didn't solve the issue. If did change the KING-TMP to KING-PC before but cant remember which error i got after that. As i saw the output of king.log doesn't detected males and females and list them as ambiguous i thought i ask here to know if its normal or not. Also the number of variants passed is low ? so not sure whats going on.

I am happy to try your suggestion and give you the exact error i got after i rename the KING-TMP file to KING-PC.

Update on the ubuntu os: there is no KING-TMP file instead i see a file generated on .vtools_cache/.runtime/.vtools/cache/KING-pc.ped.out_11657
`KING 2.2.2 - (c) 2010-2019 Wei-Min Chen

The following parameters are in effect:
                   Binary File :        KING.bed (-bname)

Additional Options
         Close Relative Inference : --related, --duplicate
   Pairwise Relatedness Inference : --kinship, --ibdseg, --ibs [ON], --homog
              Inference Parameter : --degree
         Relationship Application : --unrelated, --cluster, --build
                        QC Report : --bysample, --bySNP, --roh, --autoQC
                     QC Parameter : --callrateN, --callrateM
             Population Structure : --pca, --mds [ON]
              Structure Parameter : --projection
              Disease Association : --tdt
   Quantitative Trait Association : --mtscore
                Association Model : --trait [], --covariate []
            Association Parameter : --invnorm, --maxP
               Genetic Risk Score : --risk, --model [], --prevalence, --noflip
              Computing Parameter : --cpus
                   Optional Input : --fam [], --bim [], --sexchr [23]
                           Output : --prefix [KING-], --rplot

The following analyses will run separately:  --ibs --mds

KING starts at Mon Jun 17 05:34:26 2019
Loading genotype data in PLINK binary format...
Read in PLINK fam file KING.fam...
  PLINK pedigrees loaded: 903 samples
Read in PLINK bim file KING.bim...
  Genotype data consist of 0 autosome SNPs, 18 X-chromosome SNPs
  PLINK maps loaded: 18 SNPs

FATAL ERROR - 
No autosome SNPs are available. Please check your map file.
`

I hope this will shed some lights on the error i am getting?

**Comment by gaow** [comment]
It seems KING has been changing its output format. The KING pipeline is now updated to using the latest KING version 2.2.4. The latest vtools 3.0.x is 3.0.9 and can be installed via `conda`. 

```
conda install variant_tools -c bioconda
```

and to update the pipeline source code:

```
vtools admin --update_resource existing
```

Again please also make sure your KING is at version 2.2.4 as there has been a format change since at least KING version 2.1.
