### ISSUE TITLE
importing variants and no space left on device /tmp

### ISSUE THREAD

**Issue by freedomq8** [vatlab/VariantTools#113]
Hi there, 
I am importing a number of files some of them are large in size. I got no space error as result (assumption)  "/tmp" folder filled the up free space. is there a way to direct the temporarily importing files to another path (with more space)?

I am using vtools 3.0.3 version and importing with --store sqlite option with -j140

**Comment by BoPeng** [comment]
I am on the road and cannot find the details but please check doc for vtools admin for an option to set temp directory.
