### ISSUE TITLE
Compatibility with gcc 7.2

### ISSUE THREAD

**Issue by BoPeng** [vatlab/VariantTools#116]
It has been reported that variant tools cannot load if compiled with gcc 7.2. It might be caused by the use of embedded boost 1.49.0, which is quite old. We should test if upgrading boost can solve the issue.

**Comment by gaow** [comment]
Not sure if it is related, but now since version 3.0.x does not work for me (#120) I'm reverting to version 2.7.0. But unfortunately the conda installation does not work either (`conda install -c bpeng variant_tools==2.7.0`) because of obsolete environments. So I try to source compile:

```
pip install https://github.com/vatlab/varianttools/archive/vtools-2.7.1.zip
```

and get

```
                            ^~~~~~~~
  variant_tools/cgatools_wrap.cpp: In function ‘void right_trim_or_left_extend(cgatools::reference::CrrFile*, std::vector<std::__cxx11::basic_string<char> >&, uint32_t&, int, uint32_t&, uint32_t&)’:
  variant_tools/cgatools_wrap.cpp:5181:17: warning: unused variable ‘ref_len’ [-Wunused-variable]
               int ref_len = 0;
                   ^~~~~~~
  variant_tools/cgatools_wrap.cpp: In function ‘std::__cxx11::string normalize_variant(cgatools::reference::CrrFile*, PyObject*, size_t, size_t, size_t, size_t)’:
  variant_tools/cgatools_wrap.cpp:5236:34: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
       char * chr = PyUnicode_AsUTF8(chr_obj);
                    ~~~~~~~~~~~~~~~~^~~~~~~~~
  variant_tools/cgatools_wrap.cpp:5246:34: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
       char * ref = PyUnicode_AsUTF8(ref_obj);
                    ~~~~~~~~~~~~~~~~^~~~~~~~~
  variant_tools/cgatools_wrap.cpp:5247:34: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
       char * alt = PyUnicode_AsUTF8(alt_obj);
                    ~~~~~~~~~~~~~~~~^~~~~~~~~
  variant_tools/cgatools_wrap.cpp:5258:31: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
           chr = PyUnicode_AsUTF8(PyList_GetItem(rec, chr_idx));
                 ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  At global scope:
  cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
```

I wonder if we should at least try to make `conda install` work for version 2.7.0?

**Comment by BoPeng** [comment]
This is caused by a change in gcc 7.2, and might have the same source as this ticket. Let me have a look.

**Comment by BoPeng** [comment]
@gaow Please check out branch 2.7.2 and see if you can compile. I will create a bioconda release if it works.

**Comment by gaow** [comment]
@BoPeng I confirm that 2.7.2 works. I can test out the conda 2.7.2 release with the ISMB tutorial I had, once it is uploaded.

**Comment by gaow** [comment]
But please let me know if you prefer that I test the source compiled 2.7.2 on that tutorial, report errors then if all good we release that on conda. I can do that later this afternoon though after 2pm.

**Comment by BoPeng** [comment]
Please use the source build as it will take a while for variant tools to be accepted by bioconda.

**Comment by BoPeng** [comment]
Tried gcc 8 and did not notice any problem with the current trunk. Closing for now.
