### ISSUE TITLE
vtools export bug

### ISSUE THREAD

**Issue by gaow** [vatlab/VariantTools#128]
With version 3.0.8 and the test data in #120 I have this error when running the annotation pipeline:

```
$ vtools execute ANNOVAR geneanno

INFO: Executing ANNOVAR.geneanno_0: Load specified snapshot if a snapshot is specified. Otherwise use the existing project.
INFO: Executing ANNOVAR.geneanno_10: Check the existence of ANNOVAR's annotate_variation.pl command.
INFO: Command annotate_variation.pl is located.
INFO: Executing ANNOVAR.geneanno_11: Determine the humandb path of ANNOVAR
INFO: Running which annotate_variation.pl > /home/jovyan/.vtools_cache/annovar.path
INFO: Executing ANNOVAR.geneanno_14: Download gene database for specified --dbtype if they are unavailable
INFO: Running annotate_variation.pl --buildver hg19 -downdb refGene /home/jovyan/bin/humandb
INFO: Executing ANNOVAR.geneanno_20: Export variants in ANNOVAR format
INFO: Running vtools export variant --format ANNOVAR --output /home/jovyan/.vtools_cache/annovar_input
ERROR: INFO: Using primary reference genome hg19 of the project.
ERROR: ERROR: name 'JoinFields' is not defined
ERROR: 
ERROR: Failed to execute step geneanno_20: Execution of command 'vtools export variant --format ANNOVAR --output /home/jovyan/.vtools_cache/annovar_input' failed after 00:00:00 (return code 1).
```

**Comment by gaow** [comment]
@BoPeng to make it easy for you to test out pipelines, here are 3 external tools involved:

[extern_tools.tar.gz](https://github.com/vatlab/varianttools/files/3775488/extern_tools.tar.gz)

Also, the annotation database is shipped with the test data-set which can now be downloaded from:

http://statgen.us/files/vat-data.tar.bz2

This should allow you to run all steps for that notebook under Linux for a test. Notice you need to put `annotate_variation.pl` script to the `bin` folder, and make sure it is part of the `PATH`

**Comment by BoPeng** [comment]
I get

```
ERROR: Failed to execute step king_41: Output file ..../KING-pc.ped does not exist after completion of the job
```

Otherwise, all bugs should have been fixed (not the performance ones).

**Comment by gaow** [comment]
`..../KING-pc.ped` looks wrong ... [on this page](https://gaow.github.io/ismb-2018/#MDSanalysisandPCadjustment) it runs under `.vtools_cache` it seems. Is the file there when you check it?

**Comment by BoPeng** [comment]
It is under `.vtools_cache`, I just did not copy the entire message (because copy/paste did not work across vm + vnc.)

**Comment by BoPeng** [comment]
As far as I can tell, nothing has been changed between vtools 2 and 3 since it involves only the master sqlite database. I do not understand why vtools 3 is slow here.

Still trying to reproduce it with a rotary disk.

**Comment by gaow** [comment]
> It is under .vtools_cache, I just did not copy the entire message (because copy/paste did not work across vm + vnc.)

It looks like your `king` command did not work ... because I just checked it works on my end. So I guess this is nothing to worry about?

> Still trying to reproduce it with a rotary disk.

Check it here: 

http://205.208.52.221:1208

You should be able to login this desktop and see. It's running a docker container but the disk is a regular hard drive.

**Comment by BoPeng** [comment]
I have no idea why `-flip` takes so much time. It involves only two SQL queries (https://github.com/vatlab/varianttools/blob/master/src/variant_tools/liftOver.py#L202) and both should be relatively fast for this tiny database.

**Comment by BoPeng** [comment]
Ohmm, this server uses vtools 2.7.x, right?

**Comment by BoPeng** [comment]
It would be helpful if you could add `vi` to the docker image so that I can modify the `.py` file in place to check a few things.

**Comment by gaow** [comment]
No it uses version 3.0.8. Actually even without `--flip` it is still kind of slow ...

> It would be helpful if you could add vi to the docker image

Hmm maybe for now use the text editor provided by JupyterLab?

**Comment by BoPeng** [comment]
> No it uses version 3.0.8. 

![image](https://user-images.githubusercontent.com/9889312/67650146-c6fcf800-f909-11e9-9b8b-0553eba1fec9.png)

Perhaps I was using a previous instance?

**Comment by gaow** [comment]
oops, sorry, I just reset the server to make sure you are on the right version. This version also has `vim` installed. 

http://205.208.52.221:1197

If you pull the source code please do it under `work` directory so it will be saved there physically on the hard drive.

**Comment by BoPeng** [comment]
Well, turns out to be a very silly bug.... will need to fix it also in 2.7.x if you will be using that version.

**Comment by gaow** [comment]
haha that's exactly what I suspected going on :) Thanks for catching it. I think I'm in good position to use version 3.0.9 now, after you release it. But before that it would be great if we can verify the `KING.pipeline` works. Could you double check if running `king` command in your VM's terminal works? That's what I suspect the reason of failure in `king_41` step. If it works, then the new `KING.pipeline` file should be used in updated 3.0.x releases (and on the resource server). The `KING` pipeline indeed works on release 3.0.8 though, using my modified pipeline file.

**Comment by BoPeng** [comment]
I have king 2.2.4, and your VM has king 1.4, might that be the problem?

**Comment by gaow** [comment]
I see ... I think we may want to make it work for the newer KING version. I just stepped outside. Will be back in 10min and work on the pipeline to make changes if necessary and let you know

**Comment by BoPeng** [comment]
I just released variant tools 3.0.9, hopefully only the pipeline needs to be updated.

**Comment by gaow** [comment]
Thank you. Indeed KING.pipeline needs a fix and I've fixed it.

https://github.com/vatlab/varianttools/blob/vtools-2.7.2/pipeline/KING.pipeline

it now works with KING version 2.2.4. Would you please upload it to the resource server?

**Comment by gaow** [comment]
Also, when you release 3.0.9 it will also be released to `bioconda`? I guess I just have to wait a for while to install it. On my docker I rely on `conda install` for vesion 3.0.x.
