### ISSUE TITLE
gene base annotation

### ISSUE THREAD

**Issue by dridk** [vatlab/VariantTools#13]
Which database to use to get gene annotation consequence ? Like intron, upstream , missense_variant, splice_acceptor_variant ...

**Comment by BoPeng** [comment]
Those are usually calculated from annova and/or snpeff and imported from their outputs. vtools has a [pipeline](https://github.com/vatlab/VariantTools/blob/master/pipeline/snpEff.pipeline) for snpEff but I am not sure if it works for recent versions of snpEff.

**Comment by dridk** [comment]
Ok , thanks for your reply . 
I assume the reason is there is no database for that. Those annotations should be computed from a reference gene database.

**Comment by BoPeng** [comment]
Exactly. These are important annotation information so we even tried to provide them natively (internal calculation) but found that ANNOVA/snpEff can do it faster and better. :-)

**Comment by dridk** [comment]
Thanks it's clearer now in my mind!
