### ISSUE TITLE
git hook for pyflakes and yapf formatter

### ISSUE THREAD

**Issue by BoPeng** [vatlab/VariantTools#132]
These will help us keep the source code in good shape.

**Comment by BoPeng** [comment]
https://github.com/google/yapf/blob/master/plugins/pre-commit.sh

**Comment by BoPeng** [comment]
https://pre-commit.com/

**Comment by BoPeng** [comment]
@jma7 Please

1. Install needed tools using

```
pip install pre-commit flake8 yapf
```

2. Check existing files using

```
pre-commit run --all-files
```

or simply
```
flake8 src/variant_tools/*.py
```
You can ignore some flake8 warnings in `.pre-commit-config.yaml`.

The goal is to make sure `pre-commit run --all-files` does not generate any warning.

Here I am using `flake8` because `pyflakes` is said to be deprecated.

**Comment by BoPeng** [comment]
Note that you can ignore `swig` generated `.py` files such as `cgatools.py` since your changes would be overwritten by `swig`. [`pre-commit`](https://pre-commit.com/) documents options to exclude files.

**Comment by jma7** [comment]
There is some compatibility issue with pre-commit and virtualenv according to https://github.com/NREL/ditto/issues/147.
I have to go through
```
conda install virtualenv
conda install pre_commit -c conda-forge
```
to make it work.
