### ISSUE TITLE
ERROR: Cannot find reference genome for build hg19: Unknown runtime error happened.

### ISSUE THREAD

**Issue by FianaNG** [vatlab/VariantTools#135]
Hi there,

I am using vtools 3.0.6 through conda, as installed on my system by smcgrath in closed issue #121 
I am trying to import my vcf file using vtools import as below:
 vtools import myfile.vcf --build hg19

This proceeded to download the hg19 reference genome through wget successfully and it is now installed as
~/.variant_tools/reference/hg19.crr

However the import to my project fails with the following error:

ERROR: Cannot find reference genome for build hg19: Unknown runtime error happened.
Traceback (most recent call last):
  File "/home/users/nighralf/.conda/envs/vtools4/lib/python3.7/site-packages/variant_tools-3.0.6-py3.7-linux-x86_64.egg/variant_tools/utils.py", line 2603, in __init__
    self.crr = CrrFile(crrFile)
  File "/home/users/nighralf/.conda/envs/vtools4/lib/python3.7/site-packages/variant_tools-3.0.6-py3.7-linux-x86_64.egg/variant_tools/cgatools.py", line 287, in __init__
    _cgatools.CrrFile_swiginit(self, _cgatools.new_CrrFile(path))
RuntimeError: Unknown runtime error happened.

I am wondering if there is a problem with the path that vtools is downloading to on my system and whether there is an option to set this manually so that the tool can locate the hg19 reference? Or do you know if this is this an issue with cgatools and processing the .crr filetype?

Thanks you very much in advance and apologies if this is a simple issue!
Fiana

**Comment by BoPeng** [comment]
The latest bioconda release is 3.0.9 (https://github.com/bioconda/bioconda-recipes/blob/a8f3199c4ad9088cba5fb0c9d02896b1d5ccf42b/recipes/variant_tools/meta.yaml) so there might be something wrong with the linux build. I am trying to reproduce the problem on a VM now and will get back to you soon.

**Comment by BoPeng** [comment]
Could you upgrade to version 3.0.9 and try again? Here is what I did:

```
conda create --name vtools python=3.7
conda activate vtools
conda install variant_tools -c bioconda -c conda-forge
vtools init test --build hg19
vtools import test/vcf/input.vcf
```
and all seems to be working correctly.

**Comment by smcgrat** [comment]
Hi again guys and sorry to have to bring another issue your way. Hopefully it is just something to do with our environment that can be easily resolved. 

Here are the steps I followed to create another coda environment to test this with
```
$ conda create --name another-vtools python=3.7
$ conda activate another-vtools
$ conda install numpy Cython gsl libboost
$ conda install "blas=*=openblas"
$ conda config --add channels bioconda
$ conda config --add channels conda-forge
$ conda install libcblas
$ export LD_INCLUDE_PATH=~/.conda/envs/another-vtools/include/
$ cd ~/.conda/envs/another-vtools/
$ git clone https://github.com/vatlab/varianttools.git varianttools
$ cd varianttools/
$ python setup.py install
```

This is the error we encounter though:
```
(another-vtools) [nighralf@jal ~]$ vtools init test --build hg19
Failed to import module (No module named '_cgatools')
Please verify if you have installed variant tools successfully (using command "python setup.py install")
```

I'd be very grateful for any assistance or advice you can provide please.

Thanks

Sean

**Comment by BoPeng** [comment]
Why did you compile from source instead of installing directly from bioconda?

**Comment by BoPeng** [comment]
Please also let me know your OS so that I can try to replicate.

**Comment by smcgrat** [comment]
> Why did you compile from source instead of installing directly from bioconda?

That is what I had done in the past so I just repeated it.

I installed into a fresh conda environment using the same steps I outlined in this issue above except instead of building from source I did a `conda install variant_tools -c bioconda -c conda-forge` instead but I am getting the same error again:

```
(more-vtools) [nighralf@jal another-vtools]$ ./bin/vtools init test --build hg19
Failed to import module (No module named '_cgatools')
Please verify if you have installed variant tools successfully (using command "python setup.py install")
```

OS details: Scientific Linux release 7.7

Thanks again.

Sean

**Comment by BoPeng** [comment]
Could you go to the installed directory `envs/another-vtools/lib/python-3.7/site-packages/variant_tools` and let me know the output of command `python -c 'import _cgatools'`? There should be a missing symbol from either blas or boost...

**Comment by smcgrat** [comment]
> Could you go to the installed directory `envs/another-vtools/lib/python-3.7/site-packages/variant_tools` and let me know the output of command `python -c 'import _cgatools'`? There should be a missing symbol from either blas or boost...

I must be doing something wrong here am I? This is what I get:
```
(more-vtools) [nighralf@jal variant_tools]$ pwd
/home/users/nighralf/.conda/envs/another-vtools/lib/python3.7/site-packages/variant_tools
(more-vtools) [nighralf@jal variant_tools]$ python -c 'import _cgatools'
(more-vtools) [nighralf@jal variant_tools]$ python -c 'import_cgatools'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'import_cgatools' is not defined
```

Thanks

Sean

**Comment by BoPeng** [comment]
This is strange, no error message from

```
(more-vtools) [nighralf@jal variant_tools]$ python -c 'import _cgatools'
```

means `_cgatools` is usable.  I am creating a Scientific Linux VM though.

**Comment by smcgrat** [comment]
Ok, thanks and sorry for the hassles.

**Comment by BoPeng** [comment]
This is what I am seeing

```
$ python -c 'import _cgatools'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/bpeng1/anaconda3/envs/vtools/lib/python3.7/site-packages/
variant_tools-3.1.0-py3.7-linux-x86_64.egg/variant_tools/
_cgatools.cpython-37m-x86_64-linux-gnu.so:
 undefined symbol: _ZN5boost16re_detail_10710012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9
sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE14construct_init
ERKNS_11basic_regexIcSD_EENS_15regex_constants12_match_flagsE
```
which we have seen before ( #131 ) but should not happen to a new build...

**Comment by smcgrat** [comment]
I've created a clean conda env as per your instructions in the 3rd comment in this thread to make sure the additional steps I had used previously weren't conflicting but am still getting the same problems. Here is what I am seeing:

```
(toolsv) [nighralf@jal variant_tools]$ /home/users/nighralf/.conda/envs/toolsv/bin/vtools init test --build hg19
Failed to import module (No module named '_cgatools')
Please verify if you have installed variant tools successfully (using command "python setup.py install")
(toolsv) [nighralf@jal variant_tools]$ python -c 'import _cgatools'
(toolsv) [nighralf@jal variant_tools]$ pwd
/home/users/nighralf/.conda/envs/toolsv/lib/python3.7/site-packages/variant_tools
```

There is a system boost library installed but isn't being referenced by the users environment, conda shouldn't be aware of it or being influenced by it.

**Comment by BoPeng** [comment]
This looks like a gcc issue (eg use of c++11 and libstdc++) with this os and version of gcc. I will continue to investigate it.

**Comment by smcgrat** [comment]
Are there recommended versions of gcc? Or even ones to avoid? I can try to build with those if it would help.

Thanks

Sean

**Comment by BoPeng** [comment]
I am trying to embed different versions of boost and check if it is a boost or c++ problem. Hopefully I can get this sort out soon.

**Comment by smcgrat** [comment]
Thanks very much.

**Comment by BoPeng** [comment]
Embedding the old faithful 1.49.0 did not help, appears to be a compatibility problem with the compiler. [This post](https://stackoverflow.com/questions/40225571/regex-search-hpp56-undefined-reference-to-boostre-detail-106100perl-match) could have some hint.

**Comment by BoPeng** [comment]
OK. Finally I understand what is going on.

When we are using conda, and its boost C++ libraries, the libraries are compiled by the conda c++ compiler, for certain version of gcc, and certain flags, and in this case `-std=c++11` was used.

When we build vtools with the conda boost c++ without the conda compiler, the system compiler is used, and in this case is not compatible with the conda c/c++ compiler, so `_cgatools.so` does not work with `boost_regex.so`.

I have just submitted a patch to use the correct flags `-std=c++11`. Please compile vtools as

```
git checkout ....
conda install gcc_linux-64 gxx_linux-64 -c conda-forge
python setup.py install
```

**Comment by BoPeng** [comment]
Note that somehow on linux I had to use `gslcblas` instead of `blas` or `cblas` and I never understand which one to use, or if it is needed at all..

**Comment by smcgrat** [comment]
Thanks, (for my own notes as much as anything), these are the steps I took
```
$ conda create --name vtools-gcc-flags python=3.7
$ conda activate vtools-gcc-flags
$ cd ~/.conda/envs/vtools-gcc-flags/
$ git clone https://github.com/vatlab/varianttools.git varianttools
$ conda install Cython gcc_linux-64 gxx_linux-64 -c conda-forge
$ cd varianttools/
```

The `$ python setup.py install` step error'd as follows:
```
/home/users/nighralf/.conda/envs/vtools-gcc-flags/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lgsl
/home/users/nighralf/.conda/envs/vtools-gcc-flags/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lboost_i
ostreams
/home/users/nighralf/.conda/envs/vtools-gcc-flags/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lboost_r
egex
/home/users/nighralf/.conda/envs/vtools-gcc-flags/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lboost_f
ilesystem
collect2: error: ld returned 1 exit status
error: command '/home/users/nighralf/.conda/envs/vtools-gcc-flags/bin/x86_64-conda_cos6-linux-gnu-c++' failed with exit status 1
```

Should I install gsl and or boost via conda and if so are there specific versions I should use?

Best

Sean

**Comment by BoPeng** [comment]
> cannot find -lboost_filesystem

```
conda install boost-cpp -c conda-forge
```

**Comment by smcgrat** [comment]
Next stumbling block is:
```
/home/users/nighralf/.conda/envs/vtools-gcc-flags/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lgsl
collect2: error: ld returned 1 exit status
error: command '/home/users/nighralf/.conda/envs/vtools-gcc-flags/bin/x86_64-conda_cos6-linux-gnu-c++' failed with exit status 1
```
Sorry about all the hand holding needed here.

**Comment by BoPeng** [comment]
```
conda install libgsl -c conda-forge
```
or perhaps `gsl`.

**Comment by smcgrat** [comment]
> ```
> conda install libgsl -c conda-forge
> ```
> 
> or perhaps `gsl`.

Think `gsl` is required. The build failed with just `libgsl` but I left both installed for the build.

Also needed to `conda install curl`

But getting the same error as before though:
```
$ vtools init test --build hg19
Failed to import module (No module named '_cgatools')
Please verify if you have installed variant tools successfully (using command "python setup.py install")
```

What am I doing wrong here?

**Comment by BoPeng** [comment]
Let me create a shell script from my SL vm.

**Comment by smcgrat** [comment]
Thanks

**Comment by BoPeng** [comment]
These are the commands that are working on the VM

```
conda create --name vt python=3.7 -y
conda activate vt
conda install Cython numpy boost-cpp gsl curl gcc_linux-64 gxx_linux-64 -c conda-forge -y
git clone https://github.com/vatlab/varianttools vt3
cd vt3
python setup.py install
```

**Comment by smcgrat** [comment]
Thanks, that looks like it has worked. I'll check with the user to make sure. Thank you very much for your work.
