### ISSUE TITLE
Customized reference genome

### ISSUE THREAD

**Issue by gaow** [vatlab/VariantTools#15]
Not sure if it is possible, but I'm wondering if we can analyze genomes other than human. I think a couple of years ago we got asked about analyzing mouse genome but I forgot how it turned out. Is it possible to init a vtools project given reference genome (in completegenomics crr format, if not fasta)? For example `vtools init project --build /path/to/reference/genome`? In that way we can annotate / filter data from other species.

**Comment by BoPeng** [comment]
This is already possible. You need to first convert fasta to .crr using [vtools admin](http://varianttools.sourceforge.net/Vtools/Admin#toc11), and put the .crr file in a designated folder. The real problem is the lack of annotation databases for these genomes.

**Comment by gaow** [comment]
I see, thanks! Yes that's the wiki page I could not locate! It is very easy to load annotations in customized format and I believe people whose research focus are on non-human species should already have some annotations at hand that can be used here.
