### ISSUE TITLE
Hg38 support

### ISSUE THREAD

**Issue by akshayzawar** [vatlab/VariantTools#152]
Is there hg38 genome build for human genome available in variant_tools? I could not find any help with regard to this.

Thanks,
Akshay

**Comment by BoPeng** [comment]
What happened if you specify hg38 as parameter of --build? It should use hg38 as default reference and download it's reference genome.l

**Comment by akshayzawar** [comment]
Thank you for your reply. The documentation doesn't mention about hg38 genome build. That's where I got confused. However, hg38 in --build option seems to be working. 

You may need to update the documentation.

**Comment by BoPeng** [comment]
> You may need to update the documentation.

It is certainly mentioned somewhere, but I guess not obvious enough.
