### ISSUE TITLE
SPECFILE not available in Variant Simulation Tools

### ISSUE THREAD

**Issue by enigmargs** [vatlab/VariantTools#153]
Hi,

I'm trying to use the existing simulation models and I've installed VST using conda (v 3.1.3) and my python version is 3.8.10.
When I run, `vtools show simulation SPECFILE` it throws error _ERROR: Unrecognized simulation model neutral: Failed to download pipeline specification file neutral.pipeline: Failed to download simulation/neutral.pipeline because it is not in the variant tools online repository or local stash directories._

The command `vtools simulate Peng2014_ex1 neutral` throws,
_ERROR: Failed to simulate replicate 0 of model Peng2014_ex1: Failed to execute step neutral_1: Failed to import module simuPOP.demography: No module named 'simuPOP'_

Am I supposed to install any module before running this simulation? I can't see any information on this.

Any help is greatly appreciated.

**Comment by BoPeng** [comment]
I apologize but VST has deprecated and no longer under maintenance.

**Comment by enigmargs** [comment]
Thank you @BoPeng for the quick response. 
Sad to hear that. 
I came here from [GSR site](https://surveillance.cancer.gov/genetic-simulation-resources/home/) as I want to simulate WES data for my work. Would really appreciate if you can recommend any similar software to simulate WES data like VST.

Many thanks,

**Comment by BoPeng** [comment]
There are a number of simulators. What particular features are you looking for?
