### ISSUE TITLE
Weird imported VAF float field from VCF

### ISSUE THREAD

**Issue by guillaumecharbonnier** [vatlab/VariantTools#160]
Hello, I am a new vtools user and I am facing a weird behavior while trying to remove genotypes according to VAF values.
I have produced such VAF values using bcftools filltags as follow (spaces added here for human reading):
```
0/1:37,9:46:99:.  :.  :150,0,681:. :0.195652
GT :AD  :DP:GQ:PGT:PID:PL       :PS:VAF
```
Next I have created a vcf_vaf.fmt format adding the following code to the vcf.fmt in this repository:
```
[VAF_geno]
index=9, 10:
adj=FieldFromFormat('VAF', ':')
type=FLOAT
comment=Variant Allelic Frequency, computed by bcftools fill-tags
```
Using this cutom format file, I import my vcf file and update the needed geno_info. Unfortunately, imported VAF values are completely unrelated to values from the VCF files (mostly 0,  ranging from 0 to 1). Most importantly, if I output these values multiple times I do not get the same results...
Here is a few values to illustrate:

```
!vtools output common_var "genotype('1>0', 'field=GT&missing=.')" -l 1 | cut -c 1-100
.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,0,1,0,0,1,.,.,.,.,.,.,.,.,2,

!vtools output common_var "genotype('1>0', 'field=DP&missing=.')" -l 1 | cut -c 1-100
.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,0,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,52,40,33,35,46,.,.,.,.,.,.,.

!vtools output common_var "genotype('1>0', 'field=VAF&missing=.')" -l 1 | cut -c 1-200
398,0,1005212883,32672,.,22055,398,0,.,22055,398,0,.,22055,783787567,32672,0,0,783032459,32672,398,0,65536,0,.,32764,0,0,.,22055,556836,0,.,22055,.,22055,.,22055,.,22055,.,22055,.,32764,.,32764,.,2205

!vtools output common_var "genotype('1>0', 'field=VAF&missing=.')" -l 1 | cut -c 1-200
398,0,.,32549,.,21901,398,0,.,21901,398,0,.,21901,.,32549,0,0,.,32549,398,0,65536,0,.,32764,0,0,.,21901,556836,0,.,21901,.,21901,.,21901,.,21901,.,21901,.,32764,.,32764,.,21901,1,0,0,0,.,21901,.,32549
```

I am open to alternative approaches to just replace GT calls with VAF > 0 and VAF < 0.45 to ".", including computing VAF inside vtools from AD field as I failed to do it properly while reading the doc and smashing my head on the keyboard.

**Comment by BoPeng** [comment]
Could you please send me more details about your problem, such as OS, version of Python and vtools, a sample file, `.fmt` file, and commands to reproduce the issue?

**Comment by guillaumecharbonnier** [comment]
I think the issue was related to a defective RAM in my workstation. My apologies for opening an unrelated issue to your repo. vtools is great!

**Comment by BoPeng** [comment]
Thanks for the update.
