### ISSUE TITLE
vtools use dbNSFP results in 'WARNING: Failed to download database or downloaded database unusable'

### ISSUE THREAD

**Issue by npdeloss** [vatlab/VariantTools#17]
Dear Variant Tools Developers
I attempted running 'vtools use dbNSFP' and the download process ended with:
"WARNING: Failed to download database or downloaded database unusable: Error -3 while decompressing: invalid stored block lengths"

A google search of "WARNING: Failed to download database or downloaded database unusable" took me to an expired sourceforge page for variant tools, with no cached version.

How do I resolve this error?

Thank you for your time

**Comment by BoPeng** [comment]
Did you get this message immediately or after a long time of downloading? dbNSP is huge and network connection might be a problem here.  You can try to download http://bioinformatics.mdanderson.org/Software/VariantTools/repository/annoDB/dbNSFP_gene-2_7.DB.gz directly using tools such as wget if you cannot download it from vtools.

**Comment by npdeloss** [comment]
Dear Bo Peng,
This occurred after the download, which did not take long.
I will see what I can do with a direct download of the database.

**Comment by BoPeng** [comment]
"did not take long" should be the problem... because it should take a while unless you have really good internet connection.

**Comment by npdeloss** [comment]
Understood, it was probably a connection issue.
I'll use a direct download from the aforementioned url instead.
