### ISSUE TITLE
Installation issues on Debian8 3.16

### ISSUE THREAD

**Issue by rchapleau** [vatlab/VariantTools#18]
I have been trying to install Variant Tools on my Debian 8 system and can't seem to do so whether I download the source code or install via python (2.7.9) pip. With pip I keep getting the "error: command 'x86_64-linux-gnu-gcc' failed with exit status 1" report. When I look back into the log file I can't seem to find which library is missing. I've tried updating python with python-dev and several other packages. I've also tried with python3 (3.4.2). I'm using GNU bash 4.3.30 on Debian8 3.16 with Xfce 4.10 Desktop environment.

**Comment by BoPeng** [comment]
That command-failed message indicates missing compiler. Do you have c++/gcc installed?

**Comment by rchapleau** [comment]
I have build-essential installed. I believe that package contains a c++ and gcc compiler.

**Comment by gaow** [comment]
The setup process is multi-threading. There may be some early-on errors from some CPU threads that you do not see towards the end of the log, unless you look further up. Could you post the entire error log so we can all take a look?

**Comment by rchapleau** [comment]
Here it is. I also just went and apt-get upgraded build-essential, and am in the process of downloading the source code from sourceforge to try that route again.


[vt_piplog.txt](https://github.com/vatlab/VariantTools/files/804372/vt_piplog.txt)

**Comment by gaow** [comment]
```
    boost_1_49_0/libs/iostreams/src/bzip2.cpp:20:56: fatal error: bzlib.h: No such file or directory
```

On Debian you should:

```
sudo apt-get install libbz2-dev
```

(I googled this tip but most likely it will work)

**Comment by rchapleau** [comment]
Awesome! I had found the libbz2-dev package recommendation but it didn't work. After having upgraded the build-essential package and installed the libbz2 package, I just had success! Thanks to you both for your help!

Now on to using the tools!

Cheers!
