### ISSUE TITLE
New project for VAT?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/VariantTools#2]
The new development will take a long time to complete because we will replace the core storage model and we might need to change the interface in a non-compatible way. It is possible to create a brach of varianttools but perhaps we can start a new project? I suppose we can rename command `vtools` to `vat` and start from the `import` command, and gradually move useful parts of variant tools to the new project. In the meantime, we can keep variant tools updated with updated annotation databases etc.

**Comment by gaow** [comment]
I think it makes sense to start a new project not a branch, because a branch should be potentially mergable to the trunk, which is not our case. 

VAT now has a fair page rank on Google, and, for better or worse, seems to stand out more than vtools in searches, due to a lot relevant keywords in documentation. I'm cool with a repo for VAT. 

Do you feel like having an organizational account on github for the project? That feels a lot more serious and may look nicer to the grant office.

**Comment by gaow** [comment]
Another plus for an organization account for VAT is that we can have mutiple repos under the same account for different things. I mean different repos for format files, annotations, pipelines (involving SoS), cookbooks, plugins, etc. , in addition to the package core code.

**Comment by BoPeng** [comment]
Good idea. I will look into an organizational account. We have dedicated funding for web service storage etc and should be able to afford even a dedicated server.

**Comment by BoPeng** [comment]
VAT is taken, just created https://github.com/VariantAssociationTools/ with repository VAT. There will be other repositories such as web, resources etc.

**Comment by gaow** [comment]
Indeed ... there are way too many inactive projects under catchy names on github!

**Comment by gaow** [comment]
But at least we can have some logo to build an identity -- posting these from a few years ago here if you want to use it. 

![logo](https://cloud.githubusercontent.com/assets/917985/16244193/880316ce-37c0-11e6-919b-82242173aec6.png)

[logo.pdf](https://github.com/BoPeng/VariantTools/files/326475/logo.pdf)

**Comment by gaow** [comment]
Also, https://github.com/vatlab is not taken. I was thinking that a shorter name might do us good, say, 

https://vatlab.github.io 

for documentations, or http://vatlab.org for resources. Just suggesting.

**Comment by BoPeng** [comment]
Seems to be a better name than VariantAssociationTools... :-)
