### ISSUE TITLE
GnomAD resource and splitting multiallelic entries when importing VCF

### ISSUE THREAD

**Issue by AlesMaver** [vatlab/VariantTools#21]
Recently, I attempted to include the GnomAD dataset (provided as the sites VCF) to our exome annotation pipeline, based on varianttools. Doing so, I encountered an issue with importing multiallelic alternative allele information and also annotations for multiallelic sites. How can one handle multialleic sites when preparing custom .ann files and importing multiallic VCFs for annotations? I tried using the ExAC importing rules (ExAC.ann) file, but it it designed for tab delimited input file after multiallelic sites have already been split, not for VCF originally provided by GnomAD team. 

Thank you in advance for any guidance on this!

**Comment by BoPeng** [comment]
vtools has limited support in this case in the sense that it can import multiple alleles but cannot guarantee that variant info fields are separated correctly, because there can be many different such info fields and they can be coded in different ways for multi-allele cases.

To import annotation from vcf, you can have a look at any vcf-based annotation such as [dbSNP](https://github.com/vatlab/VariantTools/blob/master/annotation/dbSNP-hg19_138.ann). The trick is for the definition of `alt` field, that uses `CheckSplit()` to split the variants. Then, other regular info fields would be copied for all fields, and the fields that need to be split should have an `adj` function that returns a tuple, something like

```
adj=ExtractValue('EFF=',';'), lambda x: x.split('(')[0]
```
as used in [vcf.fmt](https://github.com/vatlab/VariantTools/blob/master/format/vcf.fmt).

If you are having difficulty in splitting the fields, you might want to find some vcf tools that can split multiple alternative alleles, I can easily google a few but I do not know how well they work.

**Comment by AlesMaver** [comment]
Thank you for your prompt reply! I have used GATK's VariantsToTable to convert the GnomAD VCF to a tabular format, which also allows for multiallele splitting. I am encountering another possible issue now with importing indels. For example, the GnomAD table generated from VCF file has the following entry:
#CHROM POS REF ALT
8 38285913 G GTCA

however, my own VCFs that I want to annotate are imported in this manner
#CHROM POS REF ALT
8 38285914 - TCA

Variant tools thus seem to not match the two variants and the annotation is troublesome in the case of indels. How can I tell variant tools to import the GnomAD variant table and modify the coordinate and ref/alt alleles in the same manner as it does for the VCF files (http://varianttools.sourceforge.net/Details/Variants)?

**Comment by AlesMaver** [comment]
I am also attaching the current state of my ANN file below:

```
[linked fields]
hg19=chr, pos, ref, alt

[data sources]
description=gnomAD TSV file
version=hg19_none
anno_type=variant
source_type=txt
source_pattern=

[chr]
index=1
type=VARCHAR(20) NOT NULL
comment=chromosome number

[pos]
index=2
type=INTEGER NOT NULL
comment=physical position on the chromosome as to hg19 (1-based coordinate)

[ref]
index=3
type=CHAR(255) NOT NULL
comment=reference nucleotide allele

[alt]
index=4
type=CHAR(255) NOT NULL
comment=alternative nucleotide allele

[GnomAD_AF]
index=6
type=FLOAT
comment=gnomAD Frequency

[GnomAD_AC]
index=5
type=INTEGER
comment=gnomAD Allele count

[GnomAD_Hom]
index=7
type=INTEGER
comment=gnomAD Allele count
````

**Comment by BoPeng** [comment]
variant tools is supposed to normalize variants after they are imported so your example should work. i can have a look if you could provide a simple working example that demonstrate the bug (namely a vcf file and a txt file and an .ann file to import variant from txt file).

**Comment by AlesMaver** [comment]
Dear Bo,
after an inspection of the input file, I have to say you are right. 
The original VCF has the following entry:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE
chr8    38285913        .       G       GTCA    1614.73 PASS    AC=1;AF=0.500;AN=2;BaseQRankSum=-1.635;ClippingRankSum=-0.031;DP=86;ExcessHet=3.0103;FS=3.161;MLEAC=1;MLEAF=0.500;MQ=60.25;MQRankSum=-0.891;QD=21.25;ReadPosRankSum=0.828;SOR=0.376;set=variant2   GT:AD:DP:GQ:PL  0/1:33,43:76:99:1652,0,1255
```

However the ExAC annotation has these entries:
```
8       38285913        GTCA    G       36      1.50645e-04     0
8       38285913        GTCA    GTCATCA 64      2.67814e-04     0
8       38285913        GTCA    GTCATCATCATCA   1       4.18459e-06     0
8       38285913        GTCA    GTCATCATCA      3       1.25538e-05     0
```

I am quite sure that our VCF variant corresponds to the second ExAC variant in the list above, but I am not quite sure why the variants in ExAC source are stored in such a complex way. I think the ExAC team has addressed this an idea on how to solve this issue nicely: http://www.cureffi.org/2014/04/24/converting-genetic-variants-to-their-minimal-representation/. 

Again thank you for the answer and I think this is solved now in terms of variant-tools.

**Comment by BoPeng** [comment]
variant tools would import the first variant as

```
8	38285914	-	TCA
```
and the latter four variants as

```
8	38285914	TCA	-
8	38285914	-  	TCA
8	38285914	-  	TCATCATCA
8	38285914	-  	TCATCA
```

so it should work if you import both data sets correctly, unless normalization is not done for the ExAC dataset, which will then be a bug.

**Comment by AlesMaver** [comment]
Thank you for addressing this. For easier debugging I have made a very simple project with 3 files attached in the ZIP file.

If you put them all into a single dir and run the code below, you can reproduce the issue:

```
vtools init DEBUG
vtools import test.vcf --build hg19
vtools use gnomAD.ann --files ExAC.test.tsv
vtools output variant chr pos ref alt gnomAD.GnomAD_Hom gnomAD.GnomAD_AC gnomAD.GnomAD_AF
```

You will see that annotations do not get properly matched.

[Archive.zip](https://github.com/vatlab/VariantTools/files/883932/Archive.zip)

**Comment by AlesMaver** [comment]
Just a thought - wouldn't vtools convert the variants in this manner?
```
8	38285914	TCA	-
8	38285917	-  	TCA
8	38285917	-  	TCATCATCA
8	38285917	-  	TCATCA
```
 instead of this:
```
8	38285914	TCA	-
8	38285914	-  	TCA
8	38285914	-  	TCATCATCA
8	38285914	-  	TCATCA
```
Thank you!

**Comment by BoPeng** [comment]
I got

```
$ vtools output variant chr pos ref alt gnomAD.GnomAD_Hom gnomAD.GnomAD_AC gnomAD.GnomAD_AF
8	38285914	-	TCA	0	64	0.000267814
```

Isn't this expected?

**Comment by AlesMaver** [comment]
Dear Bo, 
I got this:
```
chr pos ref alt gnomAD.GnomAD_Hom gnomAD.GnomAD_AC gnomAD.GnomAD_AF
8       38285914        -       TCA     .       .       .
```
There must be something with my version being out of date. I will check if this is the case.

*** edit ***
I am currently running this: 
`vtools 2.6.3 (revision 2893) for Python 2.7.3`

Do you think this is the cause of the problem?

**Comment by AlesMaver** [comment]
Yes, I updated the vtools version and I now get the same result! Sorry for wasting your time, I did not know that variant annotation mapping changed with the version!

Thank you so much!
Aleš

**Comment by BoPeng** [comment]
I am glad that it worked. We first relied on users to normalize variants but later realized that variants from many sources, even reputable one like this, are not normalized.

**Comment by AlesMaver** [comment]
Its great to hear that you have thought of everything. Thank you for all the efforts in developing this excellent software.
