### ISSUE TITLE
Set up Travis CI tests for variant tools for continuous intergration

### ISSUE THREAD

**Issue by BoPeng** [vatlab/VariantTools#22]
This is VERY helpful in making sure the health of the trunk as we move along.

**Comment by BoPeng** [comment]
Jun: because of the [travis CI configuration](https://github.com/vatlab/VariantTools/blob/master/.travis.yml) you will be receiving emails for failed tests.

**Comment by jma7** [comment]
Can you change the email address to junmahouston@gmail.com?

**Comment by BoPeng** [comment]
Done, but the test is not running. Something is going on and the first command fails.

**Comment by jma7** [comment]
it seems the failure is caused by "sys.exit", change back to original, the build is OK.

**Comment by jma7** [comment]
Most of the tests show passing now. Several tests are commented out and recorded in the issues.

**Comment by BoPeng** [comment]
Great. There is a large amount of warning messages but I guess we can deal with them later.
