### ISSUE TITLE
error in test_pipeline.py

### ISSUE THREAD

**Issue by jma7** [vatlab/VariantTools#31]
```vtools execute test_pipeline.pipeline createpop```shows ```ERROR: Failed to execute step createpop_10: name 'CreatePopulation' is not defined```. Right now, ```testCreatePopulation```,```testEvolvePopulation```,```testDrawCaseCtrlSample```,```testDrawRandomSample``` are commented out.

**Comment by BoPeng** [comment]
Please remove `test_pipeline` because this module is deprecated (replaced by sos).
