### ISSUE TITLE
Error: Existing database has different linking fields

### ISSUE THREAD

**Issue by MBeyens** [vatlab/VariantTools#32]
Dear

I confronted some problems during the variant association testing. I'm running the following command: `vtools associate nonsynFS001 phenotype -m "CFisher --name Fisher --alternative 2" --group_by region_name --to_db cfisher --force -j8 > cfishernonsynFS001.txt`

And I get the following error `Existing database has different linking fields (existing: {'*': ['variant_region_name']}, required: {'*': ['variant_genename']}).`

But I do not want to use variant_genename, because my intronic/UTR variants are not getting any gene name. While variant_region_name contains also gene name annotations for my intronic variants. Is there any way to change this default variable to the region_name?

Any suggestions?

Many thanks in advance

Matthias

**Comment by BoPeng** [comment]
Gao: I will handle this if this is not a trivial question for you.

**Comment by gaow** [comment]
@MBeyens We should not have any "default" -- it should be whatever field you specify. I suspect you first did a version with `--group_by genename` it generates a database `cfisher.ResultDB`. Now you use a different linking field yet the same name that confuses the program. Please verify if it is the case. the easierst way out is to change `--to_db` to another prefix.

@BoPeng if this was indeed the case we should improve the error message ...

**Comment by MBeyens** [comment]
Solved, can be closed.

Thank you!

**Comment by BoPeng** [comment]
The error message is indeed a bit vague (coming from the annotation database code) so I have updated it.
