### ISSUE TITLE
multiple fields in genotype

### ISSUE THREAD

**Issue by dridk** [vatlab/VariantTools#37]
Working : 
`vtools select denovo  -o chr pos ref alt  "genotype('','field=GT')"`

Working : 
`vtools select denovo  -o chr pos ref alt  "genotype('','field=DP_geno')"`

Not working: 
`vtools select denovo  -o chr pos ref alt  "genotype('','field=GT&field=DP_geno')"`

Do I am wrong ?

**Comment by BoPeng** [comment]
Are you trying to output two fields? I think you need to use

```
vtools select denovo -o chr pos ref alt "genotype('','field=GT')" "genotype('','field=DP_geno')"
```
