### ISSUE TITLE
Phenotype: New columns based on sample genotype and genotype information

### ISSUE THREAD

**Issue by andytokens** [vatlab/VariantTools#4]
Hi there, 

I want to add a new column to my phenotype table based on sample genotype information, and I found the following example on the website http://varianttools.sourceforge.net/Vtools/Phenotype#toc5

`vtools phenotype --from_stat "sample_alt=#(alt)"`

It seems that this function will calculate the alternative count for each subject on all variants.  Is there a way to calculate the alternative count on a subset of variants, eg, the alternative count on one gene?

Thanks.

**Comment by gaow** [comment]
Yes, for example: 

```
vtools phenotype --from_stat "sample_alt=#(alt)" --genotypes 'variant_id in (select variant_id from some_table)'
```

will select variants only from `some_table`. For your case, you may want to re-write the `(select variant_id ...)` query with a `where` clause to select variants from genes of interest.

**Comment by andytokens** [comment]
Thanks, Gao.
