### ISSUE TITLE
Can I use the merged vcf file as an input file?

### ISSUE THREAD

**Issue by o147942** [vatlab/VariantTools#41]
I have one merged-vcf file from 200 WGS data file. I merged gvcf files of 200 samples using the GATK pipeline and this makes it easier to do joint analysis and is more efficient for storage size. Do I have to split the multiple samples to import in the vtools? Can I use a merged-vcf file including multiple samples in vtools? Thanks.

**Comment by BoPeng** [comment]
You can certainly import merged vcf file.
