### ISSUE TITLE
Weighted tests

### ISSUE THREAD

**Issue by sarahmaguireICR** [vatlab/VariantTools#5]
Hi,

I've been trying to use multiple scores from dbsnpf as external weights for my association test, but all of the tests fail with the following output:

DEBUG: Association test WeightedBurdenQt failed while processing 'WRN': Operator WeightedGenotypeTester raises an exception (Cannot find genotype/variant information: dbNSFP.MutationTaster_converted_rankscore)

I've tried multiple scores, eg CADD, polyphen2 etc and the tests always fail the same way. 

This is my command 

vtools associate rare_variants aff --method WeightedBurdenBt \
--name WeightedBurdenBt --extern_weight dbNSFP.MutationTaster_converted_rankscore \
-j8 --force --to_db weighted_test --group_by variant.genename >rare_coding_variants_weighted.txt

and I'm using varianttools/2.7.0

I've tried to set the variable using  vtools update variant --set 'MT_score_converted=dbNSFP.MutationTaster_score_converted' and use this as the external weight but it makes no difference. 

I'd really like to know if there is a way around this?

Best wishes,

Sarah

Here is the output of vtools show: 

$ vtools show
Project name:                variant_association_tools_analysis_080916
Created on:                  Thu Sep  8 10:42:44 2016
Primary reference genome:    hg19
Secondary reference genome:  
Runtime options:             verbosity=1, shared_resource=/home/breakthr/smaguire/.variant_tools, local_resource=/home/breakthr/smaguire/.variant_tools
Variant tables:              common_var
                             rare_coding_var
                             rare_nonsyn
                             rare_truncating_only
                             rare_var
                             variant
Annotation databases:        dbSNP (~/.variant_tools/annoDB/dbSNP, hg19_141)
                             dbNSFP (~/.variant_tools/annoDB/dbNSFP, hg18_hg19_2_9)
                          weighted_test (weighted_test, 1.0)

**Comment by gaow** [comment]
Sorry for the late update. Just letting you know that I'm working on it.

**Comment by gaow** [comment]
To solve your issue without having to update vtools, you can try this command:

```
vtools associate rare_variants aff --method "WeightedBurdenBt \
--name WeightedBurdenBt --extern_weight MutationTaster_converted_rankscore" \
-j8 --force --to_db weighted_test --group_by variant.genename >rare_coding_variants_weighted.txt
```

The problem is that the parser for `--method` subcommand is not as smart as we hoped for now. Notice that I added a pair of `"` and dropped the database prefix `dbNSFP`. I cannot test this exact field you are using because I kept getting connection issues since last evening while downloading dbNSFP. But it works with my other test with `evs-6500` database. It should work the same way for your case -- let us know if it does not.

**Comment by gaow** [comment]
This patch  7d85c32824d781b51a041b1fa547add761399da4 improves the association command parser. With this patch the problematic command reported in this ticket is fixed.

**Comment by sarahmaguireICR** [comment]
Hi Gao,

That worked, thank you very much for taking the time to help me with this.

Best wishes,

Sarah
