### ISSUE TITLE
R error with the KING pipeline

### ISSUE THREAD

**Issue by BoPeng** [vatlab/VariantTools#56]
Command
```
vtools execute KING --var_table variant_MAFge01
```
exits with error:

```
ERROR: INFO: Gathering data for plot

ERROR: INFO: Generating dot plot 'KING.mds.pdf' ...

ERROR: ERROR: /bin/bash: /usr/local/lib/variant_tools/libtinfo.so.5: no version information available (required by /bin/bash)

ERROR: Error in ContinuousRange$new() : `inherit` must be a R6ClassGenerator.

ERROR: Calls: print ... scale_f -> continuous_scale -> structure -> <Anonymous>

ERROR: Execution halted

ERROR: 

ERROR: 

ERROR: Failed to execute step king_61: Execution of command 'vtools_report plot_pheno_fields KING_MDS1 KING_MDS2 --samples "1" --dot KING.mds.pdf --discrete_color Accent' failed after 00:00:04 (return code 1).


```

**Comment by BoPeng** [comment]
So the problem is with command
```
vtools_report plot_pheno_fields KING_MDS1 KING_MDS2 --samples "1" --dot KING.mds.pdf --discrete_color Accent
```
Dr. Leal said that this happens whenever R is involved.

**Comment by gaow** [comment]
Indeed this is a general problem trying to produce plots in R from `vtools`. We have a couple of `vtools_report` commands to generate figures from tables by calling R from commandline. But there seems lots of issues with this feature particularly the R / ggplot2 version headache. I recall over the years I've been patching such things from time to time but since ggplot2 is not backward compatible this issue has never been resolved.

Is there any general solution to it?

**Comment by BoPeng** [comment]
OK, so the problem is with `rdot` in `plot.py`? At least the error message should list the R script so that people can run the script manually to debug.

**Comment by BoPeng** [comment]
A "general" solution would be moving R dependencies from variant tools to the pipeline so that they can be fixed without touching variant tools core. I have had some R code (rpy/rpy2) in simuPOP and had a lot of headache in maintaining it. I simply removed all these features in a recent release.

**Comment by gaow** [comment]
I believe for `vtools_report` there is an option like `--save_Rscript` to output script to project folder for running it manually. Maybe that should be added to the pipeline by default?

**Comment by BoPeng** [comment]
Basically we need to check the return value of `runCommand` in `plot.py` and output `R` script when the script failed.

**Comment by BoPeng** [comment]
More info from user:

OS: Ubuntu 16.04.3
R: 3.2.3
ggplot2: 1.0.1

If it helps, I’ve tried linking the system version of libtinfo.so.5 into the program, and that fixed this error
       ERROR: ERROR: /bin/bash: /usr/local/lib/variant_tools/libtinfo.so.5: no
       version information available (required by /bin/bash)

The other errors persisted after the change.

The data files which are being used can be found here.

https://statgen.research.bcm.edu/index.php/Genassoc2017

**Comment by gaow** [comment]
Okey `ggplot2` version 1.X is quite different from version 0.X (on which `vtools` was based) so Im not surprised ...

**Comment by BoPeng** [comment]
I have

```
other attached packages:
[1] ggplot2_2.2.1
```
on my system, so supposedly 2.2.1 is more different from the 0.x used in `vtools`.

Anyway, I suppose the command is used in the SEQPower section of https://statgen.research.bcm.edu/index.php/2016-genetic-association-commands and will try to reproduce it. 

Note that the KING pipeline is not compatible with Mac (it uses a version of `sed` that is not compatible with mac's (old) `sed` among other things) so I will have to find a linux VM for the testing.

**Comment by gaow** [comment]
> Note that the KING pipeline is not compatible with Mac

My bad. I did not have a Mac back in 2014 (still no Mac desktop now). So let's fix it together ... here is the Mac binary:

http://people.virginia.edu/~wc9c/KING/Download.htm

So maybe grabbing the proper binary will fix the issue and there is no need to find a VM on your end? I also believe those 2 lines of `sed` is to replace space with `\t` and to add header `sample_name` to the beginning of file, so I guess you can feel free to replace them with `perl` or other `sed` syntax.

It may also be good idea to upgrade to version 2.2.1. Typically the actual syntax change is minimal yet crucial. It is just annoying that we have to upgrade it from time to time but I now trust that backward compatibility is better now that ggplot2 has entered version 2.2.1 so hopefully there wont be a lot changes in the future and we can avoid inventing new solutions?

**Comment by gaow** [comment]
Also for `PLINK` there is now version 1.9. The only difference is that you'll just have to drop `--noweb` option.

**Comment by BoPeng** [comment]
Well, seqpower does not support Python3 or Mac (clang)... a guess a VM has to be used.

**Comment by gaow** [comment]
Wait, we are talking about `KING` pipeline on `vtools`, right? (though SEQPower does work with Python 2 on Mac once upon the time). Indeed SEQPower does not support Python 3. 

> guess a VM has to be used.

Here is the docker file for SEQPower, if it helps ...

https://github.com/gaow/SEQPower/blob/master/Dockerfile

I also added you to that repo

**Comment by BoPeng** [comment]
I was trying to follow the teaching command sequence, which has seqpower before vtools, but now I realize that they are separate.

**Comment by gaow** [comment]
yes the course wiki page was a bit misleading. Only the vtools related commands after `vtools init VATDemo` is to be reproduced. 

SEQPower is self-contained so the docker image works well so far. Not so much for vtools -- at least we'll have to keep up with R / R-skat / ggplot2 ...

**Comment by BoPeng** [comment]
[idata.txt](https://github.com/vatlab/VariantTools/files/1643991/idata.txt) (input data generated from KING pipeline)

[plot.txt](https://github.com/vatlab/VariantTools/files/1643992/plot.txt) (a R script, named .txt for uploading to github).

On my system (mac with R 3.4 and ggplot 2.2.1), 

```
Rscript plot.txt < idata.txt
```
works well. I will let the user test on linux system.

**Comment by gaow** [comment]
Okey it looks like you've not touched any R code? That's interesting. 

FYI `gsed` does not come with standard Debian Linux at least.

**Comment by BoPeng** [comment]
No, I fixed `cut + seq`, replaced `sed` with `gsed` and I was able to run the pipeline successfully.

**Comment by BoPeng** [comment]
I have to admit that I do not understand the `sed 1i` command in `king_51` so I dared not to touch it.

**Comment by gaow** [comment]
> I have to admit that I do not understand the sed 1i command in king_51 so I dared not to touch it.

It's just adding, in place, "sample_name" header to the file. you can replace it with whatever you come up with, that does the same thing.

**Comment by BoPeng** [comment]
They will be replaced by SoS pipelines later so I will keep them as they are for now.

**Comment by gaow** [comment]
Okey then we should make a `${sed}` variable that says `sed` for Linux and `gsed` for Mac:

https://github.com/vatlab/VariantTools/blob/master/pipeline/KING.pipeline

**Comment by gaow** [comment]
I think it works now:

https://gaow.github.io/ismb-2018/index.html#MDS-analysis-and-PC-adjustment
