### ISSUE TITLE
Can not run simulations in Peng2014_ex1

### ISSUE THREAD

**Issue by BoPeng** [vatlab/VariantTools#61]
I'm a new user to variant tools and I'm trying to use variant simulation tools to generate some DNA sequence for my bachelor thesis. 

I encountered the error 

```
ERROR: Failed to simulate replicate 0 of model Peng2014_ex1: Failed to execute step neutral_40: in method 'Simulator_evolve', argument 7 of type 'int' 
```
when I try to run `vtools simulate Peng2014_ex1 neutral`. And the same error occurs as well when I run the model `resample` and `with_selection`. Here is the screen shot for the error.

![image](https://user-images.githubusercontent.com/9889312/38176200-7acca2e6-35b0-11e8-91dc-ce265fb215f3.png)

I use Python 3.6.4 in an Anaconda 5.1.0 distribution. I installed simuPOP 1.1.8.3 using conda, and variant-tools 2.7.0 using pip. I didn't use conda to install variant-tools because variant-tools is conflicting with some packages in conda when I try `conda install variant_tools`, but `pip install variant_tools` somehow works. 

I located the error function `simuPOP._simuPOP_std.Simulator_evolve()` and the module `simuPOP._simuPOP_std` in `/home/user/anaconda3/lib/python3.6/site-packages/simuPOP/_simuPOP_std.cpython-36m-x86_64-linux-gnu.so`, and this is where I can't dig in any further because I don't know how to read the `.so` file. 

Help me please! Appreciate in advance!

**Comment by BoPeng** [comment]
The offending code is around [this line of code](https://github.com/vatlab/VariantTools/blob/master/variant_tools/simulation.py#L954), let me see if I can reproduce.

**Comment by BoPeng** [comment]
The problem was with the use of python3 and should have been fixed. Please update to the latest version of variant tools (`git clone`, `python setup.py install` etc) and try again.

**Comment by Song1201** [comment]
I followed you instructions and it works!  Thank you very much!
