### ISSUE TITLE
Some typos in the vtools documentation

### ISSUE THREAD

**Issue by BingLi17** [vatlab/VariantTools#65]
1. [Tutorials->Quick start guide->3.Import an example data set](http://varianttools.sourceforge.net/Tutorial/QuickStart):

ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/pilot_data/release/2010_07/exon/snps/CEU.exon.2010_03.sites.vcf.gz
ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/pilot_data/release/2010_07/exon/snps/JPT.exon.2010_03.sites.vcf.gz

should be

http://ftp-trace.ncbi.nih.gov/1000genomes/ftp/pilot_data/release/2010_07/exon/snps/CEU.exon.2010_03.sites.vcf.gz
http://ftp-trace.ncbi.nih.gov/1000genomes/ftp/pilot_data/release/2010_07/exon/snps/JPT.exon.2010_03.sites.vcf.gz

2. [Documentation->select->Examples: Select variants by variant info fields](http://varianttools.sourceforge.net/Vtools/Select)

`% select variant 'pos < 200000' -t pos_20k 'variants with position < 20000'`

should be

`% vtools select variant 'pos < 200000' -t pos_20k 'variants with position < 20000'
`

**Comment by BoPeng** [comment]
Thanks. Please fix the sf.net doc and new doc because they are relatively easy to fix.

**Comment by BingLi17** [comment]
Sure.
