### ISSUE TITLE
Documentation: Import

### ISSUE THREAD

**Issue by jma7** [vatlab/VariantTools#67]
Examples: override sample names specified in .vcf file
``
% vtools init import -f
``
``
% vtools import V*.vcf --build hg18
``
Maybe change sample name in V2.vcf to SAMP2, sample name in V3.vcf to SAMP3

**Comment by jma7** [comment]
Import datasets in hg18 and hg19
```
% vtools init import -f
% vtools import vcf/CEU.vcf.gz --build hg18
```
The second command should be
```
% vtools import CEU.vcf.gz --build hg18
```

**Comment by jma7** [comment]
Skip 
```
2.5  Performance optimization (option --jobs and other techniques)
```
for now.

**Comment by jma7** [comment]
```
3.  Importing data in particular formats

Examples: import variant info field DP as genotype info ▸
```
Putting DP in both var_info and geno_info is confusing and maybe outdated. Consider another example.

**Comment by BoPeng** [comment]
Section `Performance optimization` can be removed.
Section on DP in both `var_info` and `geno_info` can be removed.

**Comment by BoPeng** [comment]
Can new Documentation tickets be created in the vat-docs repo?
