### ISSUE TITLE
Question about permutations in variant association tools

### ISSUE THREAD

**Issue by gaow** [vatlab/VariantTools#7]
​I try to use variant association tools to ​do my association analyses with exome data, and I find your method called WeightedBurdenBt and its permutation procedure.
In the documentation, it is mentioned that a p-value is calculated every 1000 permutations. So if we ask for 10000 permuations, only 10 p-values are calculated in the best case ?

But I would expect that a p-value is calculated at each permutation and every 1000 p-values, the lower bound of the 95 percent CI of the obtained distribution of p-values is compared to "C".
Is it really what is done ?

Could you please explain this point to me ?

Thank you
Best

Fabienne JABOT-HANIN

**Comment by gaow** [comment]
> I would expect that a p-value is calculated at each permutation and every 1000 p-values, the lower bound of the 95 percent CI of the obtained distribution of p-values is compared to "C".

Exactly. This is very similar in principle to PLINK's [adaptive permutation](http://pngu.mgh.harvard.edu/~purcell/plink/perm.shtml) though here we allow for finer control of how "aggressive" we are by letting users adjust the `C` value, the parameter for "adaptiveness". If the lower bound is greater than `C` the procedure will return the current p-value. I hope this makes it clear.

**Comment by FJ-H** [comment]
Thank you ! This is what I was expecting for !
