### ISSUE TITLE
Slow `vtools show genotype` 

### ISSUE THREAD

**Issue by gaow** [vatlab/VariantTools#79]
I have 203 samples and 6987 variants. It took quite some time to run `vtools show genotype` on this data-set with the new HDF5 implementation:

```
$ time vtools show genotypes > /dev/null

real	0m45.263s
user	0m44.636s
sys	0m0.612s
```

Do you need me to provide a test data for this?

**Comment by gaow** [comment]
Similarly for genotype related statistics:

```
vtools update variant --from_stat 'total=#(GT)' 'num=#(alt)' 'het=#(het)' 'hom=#(hom)' 'other=#(other)' 'minDP=min(DP_geno)' 'maxDP=max(DP_geno)' 'meanDP=avg(DP_geno)' 'maf=maf()'
```

**Comment by gaow** [comment]
Okay I actually had more issues down the line including genotype database loading errors. I noticed that currently `_genotype.DB` was replaced by a number of `tmp_*.h5` files ... has it been tested out in larger data-sets for the `show` and `from_stat` commands? 

To help with testing it out, here is the dataset in question:

[vat.tar.gz](https://github.com/vatlab/VariantTools/files/2149538/vat.tar.gz)

and the commands are:

https://statgen.research.bcm.edu/index.php/VAT_Commands_in_Exercise

I got stuck on this line:

```
 vtools phenotype --from_stat 'CEU_totalGD10=#(GT)' 'CEU_numGD10=#(alt)' --genotypes 'DP_geno>10' --samples "RACE=1"
```

it complains about one of those tmp h5 file not accessible even if it is there. Not sure if it can be reproduced on your end. Thank you!

**Comment by jma7** [comment]
Hi Gao, Thanks. I really need more datasets to test, so if you have some other datasets, it will be great if you could let me try. The current version is mainly optimized for "vtools import" and "vtools association" procedures.  "vtools show" and "vtools update" operation on genotypes is slower than before is expected for now, I am working on ways to make these procedures faster. I can't reproduce error from the "vtools phenotype --from_stat..." command. I will work through all the commands in the list you provided which is very helpful.

**Comment by jma7** [comment]
```vtools execute ANNOVAR geneanno```
 ```vtools output variant chr pos ref alt mut_type --limit 20 --header```
It seems these two commands are not working for sqlite version neither, where is mut_type defined?
@gaow

**Comment by jma7** [comment]
```vtools init ceu --parent ../ --variants CEU --samples "RACE=1" --build hg19```
The "init" from parent with ```--variants ---samples``` hasn't been implemented yet.

**Comment by BoPeng** [comment]
The `mut_type` stuff should be added by `ANNOVAR`. If you install annovar, you should be able to follow the ANNOVAR pipeline and see why `mut_type` is not imported.

**Comment by gaow** [comment]
Thanks @jma7 ! 

So on my end I'm now starting to test with version 2.7 but it was slow and I got stuck at liftover. So I really would hope version 3.0 would work soon! Sorry for the late feed back on it. 

> The "init" from parent with --variants ---samples hasn't been implemented yet.

I think we can start some tickets on features to be implemented? For my purpose, actually I think I'll remove this command if we can get version 3.0 work. Because this command was initially used to genreate a smaller focused association database that makes `vtools associate` faster. With version 3.0 it is not an issue and i'll be happy to remove it.

 As I said I got stuck on liftover now so i cannot test mut_type but it should work as this set of command has been tested by many people in the past. The only caveat is that the link i sent you might be a bit obsolete so let me working on porting the most recent commands from Word to a notebook and update you soon in 30min!

**Comment by gaow** [comment]
I confirm that everything works with version 2.7

https://gaow.github.io/ismb-2018

You can download the notebook from

https://github.com/gaow/ismb-2018

and run in SoS. In this version I removed `vtools init --variant` commands so hopefully we can get version 3.0 work for it! I'll keep migrating narratives to that SoS notebook

**Comment by jma7** [comment]
The pipeline function has been removed, right? Is there another way to run this pipeline?

**Comment by BoPeng** [comment]
I think we can restore the pipeline execution code for historical pipelines and allow the execution of sos pipelines from now on.

**Comment by jma7** [comment]
Is there a sos pipeline for ANNOVAR?

**Comment by gaow** [comment]
In my notebook above, 2 pipelines are used: ANNOVAR and KING. They were both once `vtools` pipelines and are relevant to data preprocessing and quality control of rare variant analysis. I'm not aware of an SoS implementation ...

**Comment by BoPeng** [comment]
We have more pipelines than these two so it makes sense to keep the pipeline feature. I will try to restore it today although I have a deadline to meet soon and I am not sure how much time I can spend on this.

**Comment by gaow** [comment]
It'd be great to have this feature back! Then we are only left to the slowness problem which not sure if can be resolved easily by Friday. But I'll certainly make it work with version 2.7 for the demo if it is too tight a timeline.

**Comment by BoPeng** [comment]
I have just restored the `vtools execute` command. sos supported will be added later but hopefully vtools can execute the KING pipeline now. @jma7 could you test?

**Comment by jma7** [comment]
I fixed several bugs using Gao's data and pushed to master. Other than the slowness of update command, I still have problem in running commands [79]-[85].

For command [79], I got:

```
INFO: Reading from standard input ...
INFO: Processing 78K of input data ...
ERROR: name 'p' is not defined
```
It seems the problem is caused by line 286 in plot.py.
Do you have some suggestions? @gaow 

For command [81], the problem is the known issue of ```vtools export``` #82

**Comment by gaow** [comment]
Thank you @jma7 . 

> It seems the problem is caused by line 286 in plot.py.

What version of ggplot2 are you using? Mine is 2.2.1 and I was able to make the plot. It might help to print out the actual R script called at line 286 and run it interactively? Or, actually there should be an option like `--save_rscript` that saves both data and script to debug from a separate R session that can help here? `ggplot2` version is a long standing issue. But version 2.x is now the mainstream so we better keep up with it.

**Comment by jma7** [comment]
The plot_association problem is fixed for now. It seems the bug is caused by some changes made when shifting from py2 to py3.

**Comment by gaow** [comment]
Great, thanks @jma7 ! I've update my notebook (and exported HTML), if you check out that link again. Is it true that all commands in that notebook now work for version 3.0, except for the slowness and known issue #82 ?

**Comment by BoPeng** [comment]
We have one last standing bug. That is to say, if the files are imported in batch and split into multiple hdf5 files, `vtools export` cannot yet join the samples from these files and export.

**Comment by gaow** [comment]
duplicate of #126
