### ISSUE TITLE
Vtools init - ERROR: disk I/O error

### ISSUE THREAD

**Issue by Jammcgro123** [vatlab/VariantTools#85]
Hi,
I am trying to create a project on a linux cluster.
I create my directory "test" and cd into it.
I run the command "vtools init newProj".
i get the following output:

INFO: variant tools 2.7.0 : Copyright (c) 2011 - 2016 Bo Peng
INFO: Please visit http://varianttools.sourceforge.net for more information.
INFO: Creating a new project project
ERROR: disk I/O error

Would anyone have a possible solution to this?

Thanks,
James

**Comment by BoPeng** [comment]
Are you sure you have write permission to the directory? Vtools (actually SQLite) does not work well on NFS but I have not seen an error for this simple operation. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jammcgro123** [comment]
Yes i have full permissions in this directory

**Comment by BoPeng** [comment]
@jma7 Can you replicate this at any of our machines?

**Comment by jma7** [comment]
I just tried on HTC cluster using your py27 conda image, there is no error.

**Comment by jma7** [comment]
@Jammcgro123 Hi, James, do you still have this problem? If yes, please paste your permission to the newProj folder here.

**Comment by BoPeng** [comment]
Cannot reproduce the problem and no further feedback from user.
