### ISSUE TITLE
Number of tested variants varies depending the statistical test

### ISSUE THREAD

**Issue by PedroBarbosa** [vatlab/VariantTools#87]
Hello,

I'm trying to do single gene association tests, but some methods are giving me different ```num_variants``` and ```total_mac``` counts. I'm not adjusting the MAF upper/lower bounds, so I find it weird that a different number of variants are being tested. How does it work internally ?

`vtools associate variant $phenotype -m "VTtest --name vt -p 5000" --group_by $group -j8 --force > $outdir/${outbasename}_vt.txt`
```
ann_gene_symbol sample_size_vt  num_variants_vt total_mac_vt
ACTC1           874             70              2372
MYBPC3          874             172             3750
MYH7            874             234             11113
MYL2            874             55              1865
MYL3            874             60              1638  
TNNI3           874             28              967
TNNT2           874             151             7535
TPM1            874             311             18658
```

`vtools associate variant $phenotype --method "BurdenBt --name Burden" -j8 --group_by $group --force > $outdir/${outbasename}_burden.txt`
```
ann_gene_symbol sample_size_Burden      num_variants_Burden     total_mac_Burden
ACTC1           874                     57                      237
MYBPC3          874                     145                     330
MYH7            874                     180                     484
MYL2            874                     41                      155
MYL3            874                     50                      105
TNNI3           874                     21                      69
TNNT2           874                     112                     346
TPM1            874                     236                     658
```

Best,
Pedro

**Comment by BoPeng** [comment]
@gaow Do you have any quick answer to this?

**Comment by gaow** [comment]
@PedroBarbosa for VT test you see there are more variants because that family of tests have a higher default MAF cutoff (5% I believe?). Typically we (or published literature) recommend using 5% for VT methods.
