### ISSUE TITLE
Need help with variant tools association test 

### ISSUE THREAD

**Issue by BoPeng** [vatlab/VariantTools#89]
I am working with variant tools to do association test with some exom sequencing data. I intend to implement my own test method called through tools command interface. 

I play with the tutorial on  http://varianttools.sourceforge.net/Association/RTest . The example you used to do this is the following command. 
```
vtools associate variant stroke \
-m 'RTest /path/to/regression.R --name demo --phenotype.name "stroke" --family "binomial"' \
\
-g refGene.name2 -j8 --to_db demo > demo.txt
```
I am not sure whether there is an online snapshot for this tutorial. If so, could you point me where I can get the snapshot, or how I get the dataset for this tutorial.

**Comment by BoPeng** [comment]
@gaow This was sent to my email. Would appreciate it if you have some quick answer to it.

**Comment by gaow** [comment]
I believe the R code is just the content in the first code snippet on this page:

http://varianttools.sourceforge.net/Association/RTest

The rest of the page discusses the format of the R scripts
