### ISSUE TITLE
quick start guide step 3

### ISSUE THREAD

**Issue by git-jemiller** [vatlab/VariantTools#92]
I'm going through the variant tools quick start tutorial and have encountered an error at step 3.

https://vatlab.github.io/vat-docs/documentation/tutorials/quickstartguide/

$ vtools admin --load_snapshot vt_quickStartGuide_v3 
Downloading snapshot vt_quickStartGuide_v3.tar.gz from online repository 
ERROR: Failed to download snapshot vt_quickStartGuide_v3: Failed to download snapshot/vt_quickStartGuide_v3.tar.gz because it is not in the variant tools online repository or local stash directories.

Can I get help with this issue?
thanks!

**Comment by jma7** [comment]
Hi, Please install the latest version through pip or docker and try again.

**Comment by BoPeng** [comment]
Closing since there was no follow up. Assuming problem resolved.
