### ISSUE TITLE
Error: Cannot find reference genome for build hg19 when importing vcf file to new project

### ISSUE THREAD

**Issue by mullinyu** [vatlab/VariantTools#93]
Hi, I got the following error when trying to importing to the new project just created/initiated

$vtools import --format vcf.fmt RAP070-FAT.genotypecalls.vcf --build hg19
ERROR: Cannot find reference genome for build hg19: Failed to download reference/hg19.crr because it is not in the variant tools online repository or local stash directories.

$vtools admin --update_resource
Scanning 0 files under /home/vtools/.variant_tools: 0 0.0/s in 00:00:00
INFO: 0 files need to be downloaded or updated
[mullinyu@omics tutorial]$

From the tutorial, the resource files will be automatically downloaded if being used.

Please advise.

Thanks!

**Comment by mullinyu** [comment]
An update if I changed to hg18

vtools import --format vcf.fmt RAP070-FAT.genotypecalls.vcf --build hg18
WARNING: The new files uses a different reference genome (hg18) from the primary reference genome (hg19) of the project.
INFO: Adding an alternative reference genome (hg18) to the project.
INFO: Downloading liftOver tool from UCSC
liftOver:   0.6% [>                                                             

Still have no idea why not working by using hg19?

**Comment by jma7** [comment]
Hi, please install the latest version through pip or docker and try again. Variant Tools is under active development, so if you find any bug, please let us know, Thanks.

**Comment by brankovicmarija** [comment]
Hi, I need a help. I have a problem with vtools import variants. This is the message that I got: Failed to download format specification file mypatient.fmt.fmt: Failed to download format/mypatients.fmt.fmt because it is not in the variant tools online repository or local stash directories. Also, with some usual commands, such as vtools show annotations-I got nothing, non error message or output. Thank you in advance!
Marija

**Comment by BoPeng** [comment]
What is your command? You are using `mypatient.fmt`, which must be a user-defined format file, so you will have to specify its path explicitly.

**Comment by brankovicmarija** [comment]
vtools import mypatient.selected.vcf --build hg19 this is my command, and then I got the message Failed to download format/vcf.fmt because it is not in the variant tools online repository or local stash directories. Thank you for your quick answer! And why show annotations does not work, it should be working, is not it?

**Comment by BoPeng** [comment]
Which version of variant tools are you using? To confirm if it is a problem we identified (and fixed in our newest release), could you edit `~/.variant_tools/user_options.py`, replace all `http://` with `https://` in `search_path`, and try again?

**Comment by brankovicmarija** [comment]
vtools 3.0.1 for Python 3.7.1.( I used conda to install).

**Comment by BoPeng** [comment]
Please upgrade to 3.0.2

**Comment by brankovicmarija** [comment]
Ok, I will do that and try everything again. Than you very much!!All the best!

**Comment by brankovicmarija** [comment]
When I use this command from the vtools site:conda update -c https://conda.binstar.org/bpeng variant_tools, and check the version, it is still 3.0.1?

**Comment by BoPeng** [comment]
Ohmm, I thought `conda` would update automatically with source release on github (which is the case for other packages), let me see what is going on.

In the meantime, please update `user_config.py` and see if it fixes the problem.

**Comment by BoPeng** [comment]
@brankovicmarija I have uploaded binaries for Linux and Mac to conda.

**Comment by brankovicmarija** [comment]
Dear Bo Peng, many many thanks!!Now everything is working! All the best, 
Marija

**Comment by BoPeng** [comment]
Thanks. Let us know if you notice any problem as there are some major changes in the 3.x releases.
