### ISSUE TITLE
Missing `ANNOVAR` and `KING` pipelines

### ISSUE THREAD

**Issue by gaow** [vatlab/VariantTools#96]
In my local resource folder I can find these:

```
[GW] ls ~/.variant_tools/pipeline/
ANNOVAR.pipeline  KING.pipeline
```

but not in current `master`. What happened to them? My local copies are totally functional with the 3.0 release ...

**Comment by BoPeng** [comment]
The pipelines are removed since the deprecation of VPT, but the functions are still there so you can use them. The plan was to ask a summer student to convert all VPT pipelines to SoS.

**Comment by gaow** [comment]
I see. But if they are still usable then we should provide them somewhere? I've made some changes to one of them a few minutes ago. In any case, let me just tar what I have and post here for book-keeping, until we get someone to help improving them. 


[pipeline.tar.gz](https://github.com/vatlab/VariantTools/files/2997496/pipeline.tar.gz)

**Comment by BoPeng** [comment]
I will restore the pipeline feature, but support both VPT and SoS pipelines.

**Comment by enigmargs** [comment]
Hi, I suppose pipelies are still not available since ```vtools show pipelines``` is not showing any pipelines in version 3.0.2 that I'm using. Can I use the above tar file to execute the commands separately?

**Comment by BoPeng** [comment]
```
vtools show pipelines
ANNOVAR                 Pipeline to call ANNOVAR and import results as variant info fields.
KING                    Pipeline to call KING to perform global ancestry and kinship inference, and import ancestry analysis results as phenotypes
                        into sample table.
```
works for latest version of variant tools.
