### ISSUE TITLE
Some benchmarks SQLite vs HDF5

### ISSUE THREAD

**Issue by gaow** [vatlab/VariantTools#97]
See the current status here:

https://github.com/gaow/ismb-2018/blob/dev/VAT-ISMB-2018.ipynb

I'll raise some issues below by pointing to the cells in question.

## Failures

1. Cell 58-59, Cell 61-62, consistent with observations in #95 
2. Cell 70 it failed due to the `export` command with genotypes.

## Performance issues

1. Cell 5 takes very long time to run! (@BoPeng  unlike other items, this one might not have anything to do with the new HDF5 stuff -- that means you might want to take a look at?)
2. Cell 13 on genotype summary takes very long time to run and appears to run on a single thread. 
3. Cell 40 and 42, there seems issue with closing tmp genotype files properly -- i believe i see the message because the vtools code did not close them properly and triggered the default pytable behavior.

**Comment by gaow** [comment]
@BoPeng For the slowness in Cell 5, not sure if you can reproduce it. But using previous version (version 2.7) on a cloud droplet it took 5 seconds to flip. 

I seem to recall some benchmark has been done with version 3.0 to prove it works faster than 2.x? But from my experience on that notebook alone, it seems 3.0 is slower in many commands.

**Comment by jma7** [comment]
I didn't observe the Cell 5 issue.
The slowness in Cell 13 is expected some how, because of the format of HDF5.
I will fix the Cell 40, 42 issues. 
The performance increase is mainly observed when processing large files on importing and association steps. I will post a comparison later.

**Comment by jma7** [comment]
So I tested the import and association step on a relatively large dataset with 100k variants.
The running time for the import step using SQLite is about 28 mins, the HDF5 version takes about 1.5 mins.
The running time for the association step using SQLite takes about 30 mins, the HDF5 version takes about 10 mins. The actual time for association calculation is not much faster, the difference is in the loading time.
The disk size is also much smaller for HDF5 version ( ~650M vs 3.7G)

## Import HDF5:
```
(VariantTools) BSTMC07TP062G1J:2k_high_hdf5 jma7$ ./run.sh 
INFO: variant tools 3.0.1 : Copyright (c) 2011 - 2016 Bo Peng
INFO: Please visit http://varianttools.sourceforge.net for more information.
INFO: Creating a new project importTest
INFO: Importing variants from /Users/jma7/Development/VAT/2k/100k_test_2k.vcf (1/1)
100k_test_2k.vcf: 100% [===========================================================================================================================================================================================================================] 101,507 8.9K/s in 00:00:11
INFO: 99,996 new variants (99,996 SNVs) from 100,000 lines are imported.
Importing genotypes: 100% [=========================================================================================================================================================================================================================] 99,996 1.2K/s in 00:01:21
```
## Import SQLite:
```
(VariantTools) BSTMC07TP062G1J:2k_sqlite jma7$ ./run.sh 
INFO: variant tools 3.0.1 : Copyright (c) 2011 - 2016 Bo Peng
INFO: Please visit http://varianttools.sourceforge.net for more information.
INFO: Creating a new project importTest
INFO: Importing variants from /Users/jma7/Development/VAT/2k/100k_test_2k.vcf (1/1)
100k_test_2k.vcf: 100% [==========================================================================================================================================================================================================================] 101,507 14.6K/s in 00:00:06
INFO: 99,996 new variants (99,996 SNVs) from 100,000 lines are imported.
Importing genotypes: 100% [==================================================================================================================================================================================================================] 200,000,000 129.9K/s in 00:25:40
Copying samples: 100% [==============================================================================================================================================================================================================================] 2,658 17.3/s in 00:02:33
```

## Association HDF5:

```
.....
ZZZ3         	2000                  	31                     	126                 	4                	0.472608         	0.718242
ZSWIM5       	2000                  	46                     	159                 	4.5              	0.468823         	0.724396
ZSCAN20      	2000                  	44                     	203                 	8.5              	0.236686         	1.18331
Testing for association: 100% [=====================================================================================================================================================================================================================] 2,508/1 5.3/s in 00:07:55

```

## Association  SQLite:
```
Loading genotypes: 100% [=============================================================================================================================================================================================================================] 2,000 1.4/s in 00:23:54
....
ZYG11A       	2000                  	38                     	120                 	5                	0.366843         	0.902404
ZSWIM5       	2000                  	46                     	159                 	4.5              	0.468823         	0.724396
ZZZ3         	2000                  	31                     	126                 	4                	0.472608         	0.718242
Testing for association: 100% [=====================================================================================================================================================================================================================] 2,508/1 7.2/s in 00:05:47
```

## Disk size for SQLite version
```
(VariantTools) BSTMC07TP062G1J:2k_sqlite jma7$ ls -lrth *.DB
-rw-r--r--  1 jma7  admin   3.0K Dec 27  2017 check.DB
-rw-r--r--  1 jma7  admin     0B Dec 27  2017 sqlite.DB
-rw-r--r--  1 jma7  admin    26K Dec 27  2017 sql.DB
-rw-r--r--  1 jma7  admin   3.7G Mar 22 16:50 importTest_genotype.DB
```
## Disk size for HDF5 version
```
(VariantTools) BSTMC07TP062G1J:2k_high_hdf5 jma7$ ls -lrth *h5
-rw-r--r--  1 jma7  admin    50M Mar 22 17:43 tmp_751_1000_genotypes.h5
-rw-r--r--  1 jma7  admin    50M Mar 22 17:43 tmp_501_750_genotypes.h5
-rw-r--r--  1 jma7  admin    50M Mar 22 17:43 tmp_251_500_genotypes.h5
-rw-r--r--  1 jma7  admin    50M Mar 22 17:43 tmp_1_250_genotypes.h5
-rw-r--r--  1 jma7  admin    50M Mar 22 17:43 tmp_1751_2000_genotypes.h5
-rw-r--r--  1 jma7  admin    50M Mar 22 17:43 tmp_1501_1750_genotypes.h5
-rw-r--r--  1 jma7  admin    50M Mar 22 17:43 tmp_1251_1500_genotypes.h5
-rw-r--r--  1 jma7  admin    51M Mar 22 17:43 tmp_1001_1250_genotypes.h5
-rw-r--r--  1 jma7  admin    27M Mar 22 17:46 tmp_1_250_genotypes_multi_genes.h5
-rw-r--r--  1 jma7  admin    27M Mar 22 17:46 tmp_251_500_genotypes_multi_genes.h5
-rw-r--r--  1 jma7  admin    27M Mar 22 17:46 tmp_501_750_genotypes_multi_genes.h5
-rw-r--r--  1 jma7  admin    27M Mar 22 17:46 tmp_751_1000_genotypes_multi_genes.h5
-rw-r--r--  1 jma7  admin    27M Mar 22 17:46 tmp_1251_1500_genotypes_multi_genes.h5
-rw-r--r--  1 jma7  admin    27M Mar 22 17:46 tmp_1001_1250_genotypes_multi_genes.h5
-rw-r--r--  1 jma7  admin    27M Mar 22 17:46 tmp_1751_2000_genotypes_multi_genes.h5
-rw-r--r--  1 jma7  admin    27M Mar 22 17:46 tmp_1501_1750_genotypes_multi_genes.h5
```

**Comment by jma7** [comment]
I feel some of your concern comes from the fact that we didn't provide much documents on what has been changed for version 3. To make the importing and association faster, we did some trade off on some other commands, which might be able to fixed in the future. We also need to do more testing on large data sets.

**Comment by gaow** [comment]
Thanks @jma7 for the convincing benchmark. So possibly computing genotype statistic `vtools show genotypes` is the only slow command now? Also we might want to organize the genotype database a bit better as suggested in another ticket -- Those association `tmp` HDF5 files are truly `tmp` that once can remove, but not the others?

I am wondering if you are using the best compression for the `h5`, and what data type are you using for the genotypes and other genotype fields? In Python, if you use `numpy.float16` (half precision float) the size will be reduced even further? I think it is reasonable to lose some precision like this for genotype data. For our purpose. We might also be more aggressive in compression method, just to keep the genotype data size smaller.
